### ISSUE TITLE
Create operator or parameter to allow users to use the end_date (discharge date) as the index date in algorithms

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#101]
Fangfei has identified a number of algorithms that require the algorithm to use the discharge date as the index date.  The only operator that allows this is the 1in2out operator.  This discharge date is the visit_end_date in the visit_occurrence table.

asana task: https://app.asana.com/0/82031366851235/110465645496634

---
Moved from outcomesinsights/jigsaw#52
/cc @jenniferduryea

**Comment by jenniferduryea** [comment]
this can be done using the Time Window operator and selecting END in the start_date field.  Closing this out as wont fix.
