### ISSUE TITLE
Create Generic Selection Operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#106]
[GDM](https://github.com/outcomesinsights/generalized_data_model) is going to introduce myriad new vocabularies for us to use as selection operators.

I propose a generalized vocabulary operator that allows two parameters:

- The vocabulary(ies?) to choose from
- The codes for the chosen vocabulary

This is easy to implement for GDM and it's feasible to backport to OMOP v4.5+

We could also rewrite the majority of our existing selection operators to subclass this operator once we've done the backporting.

needed-by outcomesinsights/jigsaw#350

**Comment by aguynamedryan** [comment]
I might want to fold support for #99 into this operator as we might want a single operator to span multiple vocabularies, as we have done with HCPCS/CPT.

This could be done by allowing more than one vocabulary ID to live in the vocabularies.csv file.  I'll contemplate this a bit more before committing to it.

**Comment by aguynamedryan** [comment]
needs #121

**Comment by jenniferduryea** [comment]
@aguynamedryan I'm not sure how to test this. I cannot find the generic operator in the Diagram Editor.  Please advise.

**Comment by aguynamedryan** [comment]
@jenniferduryea, after discussing with @mattschultz, we decided that instead of a single operator called "Vocabulary", the Vocabulary operator will masquerade as a large number of vocabulary-related selection operators.

So, for instance, the ATC WHO operator is really the Vocbulary operator, but presents as ATC WHO in the JAM.  So too are all SEER-related operators.

So, if you're seeing those operators in the JAM, this feature is working.

**Comment by jenniferduryea** [comment]
The following selection operators are shown in the screenshot below:
![image](https://user-images.githubusercontent.com/7853238/28391223-f32fdbe2-6c91-11e7-8f5e-823bb91a9b76.png)

The only "new" operators I can see are:
  * WHO ATC
  * Drug Text String
  * ICD-10 Conditions

Please confirm that these new operators are considered the "generic" operator, related to this ticket.

I also cannot find the SEER-based operators in here.  Are they supposed to be there?

**Comment by aguynamedryan** [comment]
I forgot that at the moment SEER operators are limited to GDM.

WHO-ATC and Drug Text String are Vocabulary operator.  ICD-10 Conditions is part of #99.

**Comment by marc-outins** [comment]
Confirmed WHO-ATC operator exist in JAM

**Comment by jenniferduryea** [comment]
confirmed who atc and drug text string operators exist in JAM.  Closing out.
