### ISSUE TITLE
Enforce YYYY-MM-DD format in DateRange

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#108]
Other date formats suck.  They are ambiguous and/or hard to read.

We need to make sure we validate the format of incoming dates to match YYYY-MM-DD

**Comment by aguynamedryan** [comment]
I've already pushed this to master.  I'll tag when it's ready for testing.

**Comment by jenniferduryea** [comment]
This works for me.  I created an algorithm using the Date Range operator and an error popped up when the dates were not in correct format.  Closing.
