### ISSUE TITLE
Put quotes around string "svc-jigsaw-prod" for IMPALA_DB_OPT_REQUEST_POOL setting

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#110]
Put quotes around string "svc-jigsaw-prod" for IMPALA_DB_OPT_REQUEST_POOL setting in the .env file.  This is done during installation.

---
Moved from outcomesinsights/jigsaw#359
/cc @jenniferduryea

**Comment by jenniferduryea** [comment]
Updated.  Closing out.

**Comment by jenniferduryea** [comment]
Referencing for documentation purposes.  Amgen reported it: https://github.com/outcomesinsights/amgen_jigsaw_external/issues/81
