### ISSUE TITLE
Remove Medcode, Medcode Procedure, and Prodcode operators

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#111]
The following operators were used for oldjigsaw CPRD studies and will not be supported in future releases of Jigsaw:
 * Medcode
 * Medcode Procedure
 * Prodcode

These operators need to be removed from the JAM to prevent users from getting confused and to work on current CPRD data.  ETL specs of CPRD data will only include Read, Enttype, and Gemscript vocabularies.  

---
Moved from outcomesinsights/jigsaw#358
/cc @jenniferduryea

**Comment by jenniferduryea** [comment]
confirmed these operators do not appear in the information card.  Something to note: for existing algorithms that use the medcode or prodcode operator, the conceptql code is still retained for the algorithm.  However, the JAV does not display an algorithm and the algorithm cannot be used in the Study Builder.  This is as expected and nothing needs to be changed.  Just need to document this somewhere.
