### ISSUE TITLE
Add concept_id operator for Rxnorm concept_ids

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#113]
Amgen is bringing in JMDC data that has mapped rxnorm codes.  Amgen may be interested in using the concept_ids mapped instead of the source codes (i.e. ATC).  For ease of use, it might be easier to create a "Rxnorm concept_id" operator where the user can add rxnorm codes, Jigsaw queries those codes for concept_ids, and then queries the data for those concept_ids.

---
Moved from outcomesinsights/jigsaw#363
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
This feels similar to #106, but is probably a separate operator.  Let's discuss how we want this to look/operator and maybe fold it into Anvil.

**Comment by jenniferduryea** [comment]
JMDC data is mapped to ATC concept_ids.  The source codes are actually the JMDC specific codes, which Amgen has created a special vocabulary for.  @aguynamedryan Is this ticket still relevant?

**Comment by jenniferduryea** [comment]
I don't believe this ticket is relevant anymore.  Pending an actual use case where we want to start searching for vocabulary's mapped concept_ids in OMOP v4.5+.  Closing as "won't fix".
