### ISSUE TITLE
Replace Facets with ActiveSupport

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#117]
As much as I feel [facets](https://github.com/rubyworks/facets) is the superior gem, it conflicts in many unfriendly ways with Rails, so we need to tear it out.

**Comment by jenniferduryea** [comment]
needed-by outcomesinsights/jigsaw-diagram-editor#307

**Comment by marc-outins** [comment]
@aguynamedryan how can we test this?

**Comment by aguynamedryan** [comment]
Can't.  It's working.
