### ISSUE TITLE
Add WHO ATC operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#119]
Amgen will have WHO ATC codes for their JMDC (Japan) claims data.  They will need an operator to query these ATC codes.

**Comment by jenniferduryea** [comment]
Possibly overruled by #106 . Related to outcomesinsights/amgen_jigsaw_external#97

**Comment by aguynamedryan** [comment]
needs #106

**Comment by marc-outins** [comment]
Confirmed operator exists.  The color of the operator is grey, should it be the same color as other drug operators?

**Comment by jenniferduryea** [comment]
Created outcomesinsights/jigsaw#408 to address what @marc-outins issue.  Confirmed the operator exists and queries correct vocabulary_id 21.
