### ISSUE TITLE
Move DB_OPT processing to Sequelizer

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#120]
Any connection we establish through Sequelizer should utilize the DB_OPT feature in ConceptQL, not just connections originating through ConceptQL

**Comment by jenniferduryea** [comment]
needed-by outcomesinsights/jigsaw#370 
needed-by outcomesinsights/amgen_jigsaw_external#88 
needed-by outcomesinsights/amgen_jigsaw_external#89

**Comment by jenniferduryea** [comment]
needed-by outcomesinsights/jigsaw#369

**Comment by jenniferduryea** [comment]
@aguynamedryan how do we test for this?

**Comment by aguynamedryan** [comment]
I'm confident this is working.
