### ISSUE TITLE
Fix WITHIN/AT_LEAST for ANY OVERLAP operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#122]
Fix WITHIN and AT_LEAST for ANY OVERLAP operator.  Please see diagram of how it currently works.

![Image uploaded from iOS.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/4224bb0b-2ddb-48ee-bda7-0480c674f532/Image+uploaded+from+iOS.jpg)

Highlighted areas are cases that are being ignored (passing through when they should be discarded).  The only cases that should result from the operator has a check mark next to it.

An easier diagram to see the cases that are being pulled through the operator (and shouldn't be) is in the pic below.  The four cases are the "red" lines.

![anyoverlap.PNG](https://codetreeusercontent.s3.amazonaws.com/uploads/4224bb0b-2ddb-48ee-bda7-0480c674f532/anyoverlap.PNG)

**Comment by aguynamedryan** [comment]
In looking at this again, and thinking of what "any overlap" means, I wonder if my hand-drawn diagram isn't quite wrong.


I'll use Jen's diagram to discuss.  Her diagram clearly shows that when "at least" is applied to a RHS date range, it ends up making two date ranges with a gap of (2 * value of at least) in the middle.

We're asking if a one date range overlaps _in any way_ with another.  So, using Jen's diagram, I'd argue that **only B** is incorrect in that it has no overlap with either of the two date ranges from the RHS because B completely falls inside of the gap formed by "at least".  All other ranges (A, C, D) overlap with at least one part of the RHS.

@jenniferduryea, where/how are we employing "at least" in any_overlap and what is the motivation/intent?  That will help inform how we want to make any_overlap behave with "at least".

@markdanese, do you have any thoughts?

**Comment by jenniferduryea** [comment]
@aguynamedryan This ticket came out of a brainstorm session - specifically trying to find two outpatient visits where one of them is from a gastro specialist (inside conceptql).  The diagram below is finding one inpatient diagnosis or an outpatient visit that has any overlap within 365 days or at least 30 days from an outpatient visit from a gastro doctor. The WITHIN and AT_LEAST options are specified in the ANY_OVERLAP operator.

![image](https://user-images.githubusercontent.com/7853238/27712363-90a1e062-5cdb-11e7-815f-5bda6f15d02b.png)

If we are only going to prevent scenario B from coming through, then I think scenarios A, C, and D, are not what Amgen is looking for in this set up and I'll re-do the algo.  Or is there a better way around this?

**Comment by aguynamedryan** [comment]
Agreed.  We'll filter out A, B, C, or D

**Comment by markdanese** [comment]
In general, I think we need to have operators with clear functions, with clear names.  Even if we have to make a new operator that could fit as part of another one for clarity.  

Off the top of my head, there are really 4 flavors of window operators (each of which might have small variations):

1. x BEFORE y 
2. x AFTER y
3. x OVERLAPS y
4. x DOES NOT OVERLAP y

Some of these have variations that we might want to accommodate (I know we already do):

 - BEFORE and AFTER may want to look for times where x is AT LEAST some distance BEFORE or AFTER y
 - BEFORE and AFTER may want to look for times where x is AT MOST (WITHIN) some distance BEFORE or AFTER y
 - BEFORE and AFTER may or may not want to include some kind of overlap.  This should not be part of this operator, but should be part of overlap.
 - OVERLAPS is where things get complicated, but all of the different kinds of overlaps are already defined and can be provided as options for the operator.  This would be things like x COMPLETELY WITHIN y, x OVERLAPS START OF y, etc.  We might not need all of them, or could simplify the choices.  Or we could have a few "overlap" operators.
 - Combining OVERLAPS with AT LEAST and AT MOST isn't intuitive to me, unless we are talking about how much of an overlap there is.  I don't see a use case for that at the moment.
 - DOES NOT OVERLAP would be the same as determining OVERLAP and then choosing those records that don't qualify.

**Comment by jenniferduryea** [comment]
@markdanese What it looks like you are suggesting is that we create different parameters for OVERLAPS and create a new operator "DOES NOT OVERLAP" - is that correct? I think this is interesting but I'm not sure if we can flush this out before the 7/31 deadline.  Especially since I think we need to take existing operators and fold them into one of the new operators (i.e. fold "OVERLAPPED BY" into OVERLAPS with the "completely within" parameter).  

@aguynamedryan I was rereading your comment about how ANY OVERLAP should work and now I think you are correct in that we should be taking all of the exceptions, minus B.  Because the definition of "ANY OVERLAPS" is literally any part of an event that overlaps with another event.  Actually, I think we should change the behavior of OVERLAPS to behave the way that we are suggesting ANY OVERLAPS should behave in this ticket.  Thoughts?

**Comment by aguynamedryan** [comment]
@jenniferduryea, Overlaps has a specific meaning based on [Allen's Interval Algebra](https://en.wikipedia.org/wiki/Allen%27s_interval_algebra), which is the original inspiration for our temporal operators.  I'm still not certain that adhering strictly to those definitions is a Good Idea, I don't see a need to make Overlaps behave identically to AnyOverlap, though I can understand the confusion users will have between the two.

**Comment by markdanese** [comment]
We might want to call one operator "Any Overlap" and the other something like "Specific Overlap" (for begins, ends, or all of the other interval touches).  Or build it all into one operator where the kind of overlap is in a drop down box.

**Comment by markdanese** [comment]
Let's meet to discuss this operator and hash this all out.

**Comment by aguynamedryan** [comment]
@markdanese, @jenniferduryea, when can we meet to finalize this?

**Comment by aguynamedryan** [comment]
We'll remove the at_least option as per #135

**Comment by jenniferduryea** [comment]
Is there anything to test in this ticket?  Or have the issues been addressed in #132  and #137?

**Comment by aguynamedryan** [comment]
Nothing left to test on this ticket.
