### ISSUE TITLE
Convert Algorithms to Use New Operators

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#125]
After #106 is implemented and vetted via Broom, I'd like to have a means to convert existing ConceptQL statements to use new operator names so we can eliminate many of the operators that currently live as separate classes.

E.g., ICD-9 is supported through the Icd9 class, but could easily be supported by the Vocabulary operator.

There are two ways we could do this:

1. Have the Vocabulary operator provide metadata to support "icd9" operator
2. Convert all statements using the "icd9" operator to use the "icd9cm" operator, which is the one best supported by Vocabulary

I lean towards 1) because of its ease of implementation, but 2) is much cleaner in the long run, but might be more risky and complicated technically.

needs #106

**Comment by aguynamedryan** [comment]
This would also help with the #201 issue.

**Comment by jenniferduryea** [comment]
sending to backlog per @aguynamedryan
