### ISSUE TITLE
Text operator in ConceptQL

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#127]
Jan has requested an operator that searches for drug names in the source_value field.  He has sent an excel sheet with a list of names that they will be joining on.  Please see attached.

[sample_codelist.xlsx](https://codetreeusercontent.s3.amazonaws.com/uploads/6ce570b6-8c57-4d8a-a1f0-e7578731a444/sample_codelist.xlsx)

The excel sheet shows that the names are all lower case and one word, except for "ifosfamide/mesna".   The example sql he would use to query the native OSCER data is below, where the value from commondrugname is going stored in the drug_source_value field for Amgen CDM:

1.       select … from oscer_nonomop.medicationorder where commondrugname in (“x”,”y”,”z”,…) …
2.       select … from oscer_nonomop.medicationorder a join <study>.<codelist> b on a.commondrugname=b.drugname …

The use case is that in OSCER data, the drug name is the most precise form of identifying a drug in the native data.  Mapping to Rxnorm codes have been problematic in OMOP.  Jan would like to retain the actual drug name available in OSCER so that they can still query and get the same results as previous analyses, all through using Jigsaw.  He would like this ASAP as OSCER data is available in the next month. So I assigned this ticket to Anvil July patch.

**Comment by jenniferduryea** [comment]
[OSCER 2016 commondrugname (29JUN17).xlsx](https://codetreeusercontent.s3.amazonaws.com/uploads/3a9badae-f354-4353-9d65-dbd98d1ee852/OSCER+2016+commondrugname+%2829JUN17%29.xlsx)

Jan sent me a more complete list of drug names that do include percent signs, slashes, parentheses, dashes, periods, and spaces.  There are also commas in some, but Jan has suggested Amgen will remove those commas as part of the ETL. Are these special characters a problem?

It looks like Amgen takes all of the drug names from the native data and has an epidemiologist review the list to determine which drug name is representative of an actual drug.  So it looks like Jigsaw will have to search for the entire cell value - there does not need to be a need for sub-string text searches.

**Comment by aguynamedryan** [comment]
@jenniferduryea, Thanks for the great detail in this ticket!

Commas will need to be removed before the value is stored in drug_source_value.

If matches are supposed to be whole-field matches, not substrings, I think this operator can actually be added as part of #106 via #121.  All I need to know is:

1. What name should the operator have?
  - OSCAR Drug?
2. What is the OMOPv4 vocabulary_id assigned this operator?
3. What is the OMOPv5 vocabulary_id assigned this operator?
  - OSCARDRUGNAME?
4. What is the domain for this operator? 
  - drug_exposure?

**Comment by jenniferduryea** [comment]
@markdanese confirming you want this added to the July update?  If so, I'll let the client know.

**Comment by markdanese** [comment]
maybe you can walk me through it, but July is fine for whatever we decide.

**Comment by jenniferduryea** [comment]
After review with @markdanese we decided:
 1. the name should be generic to searching text in the drug_source_value field in case there is another dataset with drug text strings.  They could use this operator across datasets to search for exact string matches.  Current name = Drug Text String

2. vocab id will be a number assigned by Amgen.
3. will use the name of the operator = drugtextstring
4. domain = drug_exposure (or drug)

Also need to include (in information card section) that values are comma-delimited and will search for the entire string in cell (or exact match).  Substring searches are not available.  Do not include the following characters:  comma, quotes, double quotes.

Questions:  Are any other special characters a problem?  Encoding? 
Suggestions for the operator:  Ignore leading and trailing white space?  

We need to be explicit with the client so asking for clarification, not so much that we should consider doing something extra for the operator.

**Comment by jenniferduryea** [comment]
Pending response from @aguynamedryan

**Comment by aguynamedryan** [comment]
I don't think other characters will be a problem.

Because I've opted to use #121 to implement this operator, we cannot strip whitespace (although, maybe we should for all vocabulary operators?)

b72a3d6e5b526b336eeff083421309bdea2d8222 introduces this operator, but it has a bogus vocabulary ID until Amgen provides the proper one.

**Comment by jenniferduryea** [comment]
created a ticket on Amgen's side to record request: https://github.com/outcomesinsights/amgen_jigsaw_external/issues/108

**Comment by jenniferduryea** [comment]
Per James, please use the following vocabulary_id for this operator: 26400.  Thanks.

**Comment by aguynamedryan** [comment]
Updated.

**Comment by jenniferduryea** [comment]
Confirmed that this is working and querying drug_source_vocabulary_id = 26400.
