### ISSUE TITLE
Mapping File

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#128]
In order to support #115, we need [GDM's mappings table](https://github.com/outcomesinsights/generalized_data_model#mappings) to relate source-oriented genders to OHDSI gender concept IDs.

**Comment by aguynamedryan** [comment]
needed_by #115

**Comment by aguynamedryan** [comment]
@marc-outins, please start including mappings of source gender concept IDs to OMOP's standard gender concept IDs.

**Comment by aguynamedryan** [comment]
@marc-outins, can you please also include mappings for race?

**Comment by marc-outins** [comment]
This has been done for awhile.  Closing.
