### ISSUE TITLE
Make Sure Race is GDM-compatible and Supports Mappings

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#130]
We'll need to support mappings in the Race operator for it to work nicely with GDM.

**Comment by aguynamedryan** [comment]
needs #128

**Comment by jenniferduryea** [comment]
moving this to chisel since it's gdm specific and not needed for broom.

**Comment by jenniferduryea** [comment]
@aguynamedryan does Lexicon fix this issue?

**Comment by jenniferduryea** [comment]
this has been implemented.
