### ISSUE TITLE
Allow Adjustments to be Passed to Date Limitation

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#131]
#123 did a good job, but there is a new use case I hadn't considered -- many algorithms have custom (or global) minimum and maximum time windows.  Playing around with this in my head, I think I have seen an opportunity to allow adjustments to be sent into the date limiting logic.  The idea is:

We'll create a table to represent each patient's "lookback period".  But if an algorithm in the baseline has a "maximum lookback" set, we'd need to adjust the lookback period when evaluating that algorithm.  If we allow adjustments like those in TimeWindow to be passed into the date limiter, it could temporarily alter all the dates in the lookback period table before doing selection via the algorithm.

**Comment by markdanese** [comment]
@aguynamedryan algorithms should not over-ride anything set in the study builder

**Comment by markdanese** [comment]
@aguynamedryan ok -- we are good.  thanks for discussion

**Comment by jenniferduryea** [comment]
Since all of the supporting tickets are closed out, I believe we are safe to close this ticket out.  Closing.  Please reopen if there are other things we need to test.
