### ISSUE TITLE
Contains needs to modify LHS date range when applying :within

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#132]
Right now we're expanding the RHS in contains, which makes RHS events far less likely to qualify.

**Comment by aguynamedryan** [comment]
Discovered as part of talks re: #122

**Comment by aguynamedryan** [comment]
needed-by #137

**Comment by jenniferduryea** [comment]
@aguynamedryan I'm not sure how to test this.  Could you give me a scenario as to how to test?

**Comment by jenniferduryea** [comment]
i have created a diagram that will help test (and understand) how this change will affect results.  
![image](https://user-images.githubusercontent.com/7853238/28799610-20aeaf2e-75fe-11e7-95de-da59fc74ca0b.png)

**Comment by markdanese** [comment]
that is helpful

**Comment by jenniferduryea** [comment]
Tested this out and it works as described above.

**Comment by jenniferduryea** [comment]
closing out.
