### ISSUE TITLE
"Deprecate" Overlaps and OverlappedBy

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#133]
These operators are probably NOT what a user wants to use.  They most likely want to use AnyOverlap, so let's deprecate these operators and suggest AnyOverlap.

**Comment by marc-outins** [comment]
@aguynamedryan - Confirmed once the user adds the operator to the diagram a "?" icon appears.  Then if the user clicks into that they get the deprecated warning message.  It seems like the message should appear before the user adds it to the diagram.

**Comment by jenniferduryea** [comment]
confirm that I can see the warning when a user selects OVERLAPPEDBY and OVERLAPS in the Diagram Editor.  Please see screenshot below to show how the warning is shown to the user.  Just to note that the user has to select the operator, get the warning (question mark symbol on the operator), view the information card, to see the actual warning.  It's not very obvious, but I think it does the job well.  Screenshot here:
![image](https://user-images.githubusercontent.com/7853238/28646177-4b3e955c-7215-11e7-929a-d8cfa69a0a63.png)

**Comment by jenniferduryea** [comment]
For documentation purposes, the following other operators have deprecation warnings:
"overlapped_by",  true
  "observation_period",  true
  "condition_type",  true
  "drug_type_concept",  true
  "place_of_service_code",  true
  "overlaps",  true

Confirmed all of these operators display the deprecation warning.
