### ISSUE TITLE
Remove at_least from most temporal operators

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#135]
Aside from Before/After, we can't think of a good reason to keep at_least as an option for the rest of the temporal operators.

**Comment by jenniferduryea** [comment]
confirmed that the only operators with an "at_least" parameter are AFTER and BEFORE.  All other temporal operators have WITHIN and OCCURRENCES only.  AT_LEAST has been removed.

**Comment by marc-outins** [comment]
Confirmed the only operators with at_least are AFTER and BEFORE.

**Comment by jenniferduryea** [comment]
For background info, we looked at all algorithms on Amgen's PROD as of 1:00pm on 8/2/2017 and only two algorithms used the at_least parameter in temportal operators other than After and Before. The algorithm names are:
Drg all chemo date -- test
DRG cancer indexdate - test old ver.

Both algorithms were set to draft.  I'll confirm with Fangfei but I don't think these algorithms were in use - they were more sandbox type algos.  FYI.
