### ISSUE TITLE
Drug name not output when drug_concept_id is not in drug_strength table

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#139]
When a drug_concept_id is not in the drug_strength table, the drug_name is not included in the output (events) table.  Possible issue with using an INNER JOIN between temp tables during study creation.

Example record:  In synpuf_250, use patient 68 for NDC 00002021008 with drug_concept_id 19127574.  The study  in jigsaw.jsaw "drug column test" and algorithm "drug column test" exports the event without a drug name or drug_amount.

---
Moved from outcomesinsights/jigsaw#373
/cc @jenniferduryea @aguynamedryan @marc-outins

**Comment by jenniferduryea** [comment]
confirmed that the drug name now shows up in my study.  Closing out.
