### ISSUE TITLE
Fatal error in get_unique_code_list_for_vocabulary when calling ConceptQL::Datebase.query.code_list

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#140]
Get the following error when adding an algorithm to the index event section of the study builder:

NoMethodError in SentinelStudiesController#new 
undefined method `[]' for nil:NilClass
Extracted source (around line outcomesinsights/jigsaw#86): 
84 cdb = ConceptQL::Database.new(Rails.application.sequel_db)
85 q = cdb.query(statement)
86 code_lists = q.code_list(nil)
87 
88 if vocabulary.is_a? Array
89  vocabulary.map!(&:downcase)

This is an issue we've run into before that I believe Ryan has fixed

---
Moved from outcomesinsights/jigsaw#399
/cc @marc-outins

**Comment by jenniferduryea** [comment]
confirmed I can now add an index event. I think this closes out the ticket.
