### ISSUE TITLE
Events by Provider Specialty

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#141]
- Takes the same arguments as the ProviderFilter operator.
  - A comma-delimited list of specialty concept_ids
- Finds provider_ids for all providers with those specialties
- Searches any table that has an FK reference to provider-related table and selects records that match one of the provider_ids
- Potential tables searched:
  - person
  - condition_occurrence
  - procedure_occurrence
  - drug_exposure
  - observation
  - visit_occurrence
    - Gathered by finding all visits with a visit_occurrence_id that appears in the other records from other tables

**Comment by aguynamedryan** [comment]
Are we still doing this?

**Comment by jenniferduryea** [comment]
closed in lieu of this https://github.com/outcomesinsights/conceptql/issues/142. Users will then be able to use the provider specialty filter to find all relevant events for that specialty.
