### ISSUE TITLE
The Drug Use Module needs to recognize possible HCPCS codes in the CPT OR HCPCS operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#143]
Currently, the Drug Use module does not look for potential HCPCS codes in algorithms using the CPT OR HCPCS operator.  It does look for potential HCPCS codes when an algorithm uses the HCPCS operator.  We need to add the CPT OR HCPCS operator for review of potential HCPCS codes - especially since the CPT OR HCPCS operator is used more often.
needed-by outcomesinsights/jigsaw#43 

---
Moved from outcomesinsights/jigsaw#409
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
What if the algorithm includes an asterisk (#142)?  Do we dump all J-codes?

**Comment by jenniferduryea** [comment]
I would not recognize the * as potential hcpcs codes.  We also need to address this in the HCPCS operator.  I'll test this in #142 to make sure Sentinel modules are not bringing in J codes.

**Comment by jenniferduryea** [comment]
Confirmed that using the * will not prompt j code fields to show on Study Builder.  However, I'm still experiencing this original issue.  Study 9513b46a-b093-4979-b37e-f3aa46298825 on jigsaw.jsaw.

**Comment by jenniferduryea** [comment]
this seems to be fixed.
