### ISSUE TITLE
Possible Issue with DrugTextString Operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#145]
Since I implemented this operator (#127) using the generalized Vocabulary operator (#106), it will not return days supplied, drug name, etc like other drug_exposure related operators.  This is probably a Bad Thing.  

@jenniferduryea, please confirm.

**Comment by jenniferduryea** [comment]
Yeah - that's a problem.

**Comment by jenniferduryea** [comment]
Moving to v2.

**Comment by aguynamedryan** [comment]
I can't think of a quick-fix to this issue.

Records that need to return drug information are told to do so at the Class level, but all custom vocabulary operators share the same class, Vocabulary, which is not a class that will pull down drug information.

We might want to subclass Vocabulary operator as DrugVocabulary operator, but this will take some more thought.

**Comment by aguynamedryan** [comment]
We could probably look at the domain assigned to an operator in the CSV file and if it is from the drug_exposure domain we can use the proposed DrugVocabulary subclass

**Comment by jenniferduryea** [comment]
moving this to chisel for discussion

**Comment by aguynamedryan** [comment]
As part of #253, this issue was also fixed.

**Comment by jenniferduryea** [comment]
needs #253

**Comment by jenniferduryea** [comment]
I did not have any data to test with this.  But i created an algo using this operator and added as index algo to protocol builder.  COnfirmed that events output table had lab value columns, which meant that tshank recognized this operator as a drug operator and if there were values, it should be populated.  Closing out. Looks good!
