### ISSUE TITLE
Place of Service Filter is not casting to the Visit Occurrence table

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#146]
A bug has been discovered that the Place of Service Filter does not cast to the visit occurrence table, causing zero results.  

Creating a new patch milestone.

**Comment by aguynamedryan** [comment]
To be clear, PlaceOfServiceFilter will not cast to visit_occurrence.  It should, instead, join any table that has a `visit_occurrence_id` column against the `visit_occurrence` table and harvest the `visit_source_concept_id` from the joined `visit_occurrence_table`

**Comment by jenniferduryea** [comment]
Created the following algorithm (screenshot below) and used the generated sql code against synpuf250.  I found 2,458 events.
![image](https://user-images.githubusercontent.com/7853238/29983636-b420bf74-8f0b-11e7-80d9-3d3b66f7ae86.png)
I also added this algorithm to a study and ran it against synpuf250.  The study completed without errors and resulted in 13 patients.

**Comment by marc-outins** [comment]
The algorithm Acute Pancreatitis - Outcome on jigsaw.jsaw.io previously did not return records.  After the fix it now returns records.  I also looked at the generated SQL code and it now is joining against the visit occurrence table to get the place_of_service_concept_id.
