### ISSUE TITLE
Dropping Read codes when running a study

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#152]
Amgen reported odd behavior of cohorts coming back with different cohort totals for the same study.  The original solution found that a different set of Read codes were used in each of the cohorts run.  However, I started to question if the read codes reported in the export_queries output table contained all of the read codes listed in the Read operator.  It looks like, somehow the study builder was dropping read codes, somewhat randomly.  

I created study http://jigsaw.jsaw.io/studies/9b1f4347-39cd-44e3-9d77-d58e024021bd/edit using the same algorithm listed by Amgen.  The study was exported to p16_claire_001 under the latest Anvil (jigsaw.jsaw.io):
![image](https://user-images.githubusercontent.com/7853238/32128941-471c67a4-bb37-11e7-9284-673cf8d29dc1.png)

The read operator contained 16 read codes.  The SQL generated only had 14 codes.  Here are the codes found, side by side:
![image](https://user-images.githubusercontent.com/7853238/32128924-24beabcc-bb37-11e7-96f3-9d494d7f2177.png)

This seems to be consistent with Amgen's problem.  Here are a list of the Read codes found in the SQL generated from all three studies in question:
![image](https://user-images.githubusercontent.com/7853238/32128961-686398c4-bb37-11e7-85f8-3a0c11b2547f.png)

In each run, they are missing two codes. They can be different, but it's still missing two codes.  My study above is also missing two codes.  These codes are also present in the source_to_concept_map.  So I'm not sure where this is getting dropped.

AS far as I can tell, this is limited to the Read operator.  I have a feeling it has something to do with the extra sql query conceptql does to find what read codes live in what domain as per the source_to_concept_map.

---
Moved from outcomesinsights/jigsaw#432
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
46ae24e3abb81a820bcf772d316242aec27696aa introduced a bug in the Read operator so that one arbitrary Read code is dropped for each different domain that the Read operator determines it needs to search.

So, since the codes in the above example belong to two domains, two codes ended up being dropped.

**Comment by jenniferduryea** [comment]
Looked at sql generated from two studies using read codes (using one code and using 16 codes) and all codes in the operator was found in the study's sql.  I also tested this with a read code that is found in two different tables (read code = 13Wb.00) and found that the sql generated is querying at both tables for the value.  Looks great.  Closing out.
