### ISSUE TITLE
Replace all CTEs with Temp Tables

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#153]
As part of an effort to potentially improve the performance of ConceptQL on Impala, we've been told we might want to replace all uses of CTEs with the creation of temporary tables.

ConceptQL should allow us to switch between using CTEs vs temp tables with minimal effort.  Ideally, I'd like it so that ConceptQL uses CTEs at all times unless the environment variable `CONCEPTQL_FORCE_TEMP_TABLES` is set.  In that situation, all CTEs should instead be temp tables.

First off, Impala does not actually support temp tables, so we'll need a way to specify a "scratch database" that ConceptQL will use to house its "temp" tables.  Currently, Jigsaw already has such a scratch database.  Its name is stored in the `DOCKER_SCRATCH_DATABASE` environment variable.  ConceptQL should use the same variable to determine its scratch database.  If this variable is not set, but `CONCEPTQL_FORCE_TEMP_TABLES` is, we should raise an exception informing the user they must set the `DOCKER_SCRATCH_DATABASE` variable.

Because Impala doesn't support temp tables, we need to take some precautions.
- Each temp table will need its own unique name.  Perhaps when a ConceptQL statement is initialized, we could create a random string that we'd prepend to the name of all temp tables to ensure that even if a user is running an identical ConceptQL statement as another user, their two sets of temp tables have different names and don't interfere with each other
- Regardless of whether or not a statement successfully executes, all temp tables created for the statement must be removed from the scratch database before control is returned to the calling program

**Comment by jeremyevans** [comment]
I can start looking into this when I return from vacation, around November 9.

**Comment by aguynamedryan** [comment]
That's just fine!  Thanks so much!

**Comment by jeremyevans** [comment]
I've added pull request #154 for this.  It's not complete yet, just the first step to make CTE names unique.

**Comment by aguynamedryan** [comment]
This has been working for ages.  Thanks again, @jeremyevans!
