### ISSUE TITLE
Date Range operator using constant in a window function causing Impala to fail

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#157]
I ran the following study on jigsaw.jsaw.io and it failed in Impala due to using an constant in a window function: http://jigsaw.jsaw.io/studies/f49112c2-9c84-4b82-853e-65ce79073dda.  

This study contains an index algorithm that uses only the Date Range operator to specify a date.  The idea is to give everyone the same index date (i.e. prevalent studies).  Amgen was using it to find the denominator, or all patients that have a year of observation_period prior to a certain date.

Amgen originally found this error, documented here: https://github.com/outcomesinsights/amgen_jigsaw_external/issues/167

This is a bug.  Amgen has decided to wait on getting the fix in the next update, rather than create a patch.  Assigned this to Broom.

**Comment by aguynamedryan** [comment]
@jenniferduryea, please confirm this is still an issue, and, if so, please submit a test case for it.  Thanks!

**Comment by jenniferduryea** [comment]
I cannot recreate the problem.  Looks like this may have been resolved after we updated cloudera? Not sure.  But this is not an issue anymore.
