### ISSUE TITLE
Nth Occurrence Operator not pulling correct record "occurrence" for drugs with multiple drug_strength records

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#159]
Originally reported by Amgen https://github.com/outcomesinsights/amgen_jigsaw_external/issues/176, when the Nth Occurrence operator is used with certain drug records (i.e. NDC operator), the result is an event prior to the specified occurrence.  This is due to ConceptQL joining the drug_strength table to the drug_exposure records.  ConceptQL takes the drug_concept_id associated with the eligible records and joins it against the drug_strength table to get "amount" and "unit" information.  Analysis of the drug_strength table shows 22,522 out of 103,945 drug_concept_ids have more than one record in the drug_strength table.  When ConceptQL joins a drug_concept_id with multiple drug_strength records against the patient's eligible drug_exposure records, the records are effectively duplicated to reflect one patient record per drug_strength record.  Please see my test case below, done in jigsaw.jsaw.io, for a reproducible test.

The SQL from the algorithm below was applied to synpuf_250 on our HUE.

![image](https://user-images.githubusercontent.com/7853238/34852081-c321fba8-f6e1-11e7-93ce-445fb950c483.png)

For patient 189, there are two NDC records with source values 00363690010 on 4/23/09 and 12027008802 dated 8/9/10.  Since I specified "2" occurrences, the SQL should produce the 8/9/10 record.  However, it produces the 4/23/09 record.  These source values (00363690010 and 12027008802) are mapped to drug_concept_id = 974226.  This drug_concept_id has two records in the drug_strength table to represent different ingredients.  Please see below:

![image](https://user-images.githubusercontent.com/7853238/34852385-35d879c8-f6e3-11e7-8ee8-b2b0bb2f1be4.png)

ConceptQL took two patient drug records and duplicated them to reflect the two drug_strength records per one drug_concept_id.  

To fix this bug, we need to stop duplicating the patient's records so that the nth occurrence operator works as expected.  Ultimately, we need to know how we want ConceptQL to behave when there are multiple drug_strength records for one drug_concept_id - what do we choose?  Or do we leave it blank and don't join the table at all?

As background, there are two reasons why there are multiple drug_strength records:
 1. The drug has multiple amount/units or "doses" associated with the drug.  This is applicable to Amgen's case using NDC 61958110101.
 2. The drug has multiple ingredients, creating a different record for each ingredient_concept_id.

Tagging @markdanese since he originally requested the amount/unit information to be part of Jigsaw's output.  Tagging @aguynamedryan for the fix.  Assigning this to Broom.

**Comment by markdanese** [comment]
I am a little surprised about how an RxNorm code can have multiple doses.  Generally the dose is part of the definition of the CUI at the level that OHDSI is using RxNorm.  But it only takes 1 case to mess it up.  And I know they match at higher levels in cases where the lower level doesn't exist (e.g., with J codes).  So, maybe this is just a big of a mess.

My suggestion would be to join the dose as we originally proposed, if there is a unique record.  If not, then I would replace it with the word "multiple", or "multiple records", or something similar to indicate that a unique match did not exist.  

There are many studies where it is important to know the dose of the drug.  I guess we could also consider a third option where we provide a drug dose table in the output and let researchers merge it in as needed (if needed) for their study.

We can discuss this too.

**Comment by jenniferduryea** [comment]
I updated https://github.com/outcomesinsights/jigsaw/issues/436 with this comment where if there are multiple drug_strength records for a drug_concept_id, we'll use the word "multiple" in the output.  I think that's a good solution.

**Comment by markdanese** [comment]
I am not sure I follow, but please do whatever seems reasonable.

**Comment by aguynamedryan** [comment]
I opted to use -1 for drug_amount and now @marc-outins's sentinel post-processing is erroneously calculating drug amounts.

I don't think using -1 or 0 is a good idea.  I also question if NULL is ok either, because I see NULL representing that we found _no_ records, not that we found too many.

Should we consider narrowing down the drug_strength table to a single record per concept_id?

**Comment by aguynamedryan** [comment]
Argh, looks like there's ~10,000 duplicate drug_concept_ids in the drug_strength table, some concept_ids show up 16 times.

I'm still not satisfied with any of the proposed solutions to this issue.  Can we discuss tomorrow?

**Comment by markdanese** [comment]
Can we create a new concept id that represents "Multiple records" and use that?

**Comment by markdanese** [comment]
I talked with @marc-outins about this to clarify what is going on.  

It seems that the problem is related to drugs with more than 1 ingredient.  From an ingredient perspective, getting multiple rows makes sense.  But it also can be confusing to users who will be expecting one row per drug product.

I like NULL since we don't have an "NA" type to distinguish missing and not available.  This generates the expected number of rows and NULL that tells the user something is wrong.  And we don't affect any calculations (or calculations can account for NULL).  We can document this behavior in the data dictionary.

But I would be open to reporting either multiple rows or a single row with NULL.  Or reporting drug strength separately.  Or handling this in the vocabulary output table.

**Comment by aguynamedryan** [comment]
I'm ok with NULL in this case.  It's the easiest to implement.

**Comment by jenniferduryea** [comment]
Tested and confirmed that if the patient has a drug_concept_id that has multiple drug_strength records in their omop vocabulary tables, then Jigsaw will report null under the Events table output for variables drug_amount and drug_amount_units.  

A test for multiple drug_strength records is stored, named:
test_drug_strength_with_nth_occurrence.

Closing.
