### ISSUE TITLE
OCCURRENCE parameters in AFTER operator while using WITHIN setting for data spanning years

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#160]
Elizabeth from Amgen reported this problem, stating the output from an algorithm was pulling in unnecessary events.  This error was recreated on our side under broom and anvil.

I pasted the SQL for an algorithm into HUE and run against synpuf_250 and looked at results for person_id = 2 to verify the error.  The conceptql diagram is looking for the fourth diagnosis in a list of diagnoses within 60 days of each other.  Please see screenshot of diagram below:
![image](https://user-images.githubusercontent.com/7853238/36756611-62a6f5e6-1bc4-11e8-9cd9-5a63cfee7169.png)

The conceptql code is here: 
`[
  "after",
  {
    "left": [
      "icd9",
      "250.00",
      "401.0",
      "401.9",
      "459.81",
      "780.93",
      {
        "label": "dx"
      }
    ],
    "right": [
      "recall",
      "dx"
    ],
    "within": "60d",
    "occurrences": "2"
  }
]`

The table below shows what the raw data in synpuf for person_id = 2 for the diagnoses used in the algorithm, what rows are included in the expected output and what rows are included in the actual output (from HUE).

| num | source_value | end_date | + 60 days | Expected Output | Actual Output | 
| -- | -------------- | ---------- | ----------- | ------------------ | ------------- | 
|1| 355.8 | 10/4/2008 | 12/3/2008 | | | 
|2| 401.0 | 10/8/2008 | 12/7/2008 | | |
|3| 401.9 | 3/30/2009 | 5/29/2009 | | | 
|4| 401.9 | 3/30/2009 | 5/29/2009 | | | 
|5| 401.9 | 4/12/2009 | 6/11/2009 | | | 
|6| 401.9 | 4/15/2009 | 6/14/2009 | | | 
|7| 250.00 | 5/11/2009 | 7/10/2009 | x | x | 
|8| 250.00 | 5/16/2009 | 7/15/2009 | x | x | 
|9| 401.9 | 6/23/2009 | 8/22/2009 | x | x | 
|10| 401.9 | 7/31/2009 | 9/29/2009 | | x | 
|11| 250.00 | 7/31/2009 | 9/29/2009 | | x | 
|12| 780.93 | 12/6/2009 | 2/4/2010 | | |
|13| 459.81 | 1/23/2010 | 3/24/2010 | | x |
|14| 401.9 | 2/23/2010 | 4/24/2010 | | x | 
|15| 401.9 | 2/23/2010 | 4/24/2010 | | x |
|16| 401.9 | 6/26/2010 | 8/25/2010 | | |

The output shows that the algorithm outputs correct data until the patient's data begins a new year.  Then then OCCURRENCE setting is not respected on data in the new year.  This mimics what Amgen found in their data.

Some things to note for documentation purposes in conceptql_spec:
 * OCCURRENCE and WITHIN parameters are evaluated at each event found.  So at each event, conceptql is looking for the 4th event within 60 days of that initial event.
 * Occurrences are counted by each data row, regardless of when the events are dated.  So if you have multiple rows with the same date (i.e. rows 3 and 4 or 10 and 11 in the table above), each row will get it's own occurrence number.  EXCEPT, when starting to count the occurrences from a multiple-row-same-dated event.  Then that same date (regardless of the number of rows that have that same date) are counted as occurrence = 1 and the next occurrence is the next data row that is > than the end_date of the start row.  For example, using the table above, if the you are counting the occurrences at row 2, then row 2 = occurrence 1 and rows 3 and 4 = occurrences 2 and 3.  If you are counting the occurrences at row 3, then row 3 = occurrences 1 and row 5 = occurrences 2.  Row 4 has the same date as row 3 and is "considered" the same event technically.

tagging @aguynamedryan for help.  Scheduling this for broom.  

Here is Amgen's ticket for tracking: https://github.com/outcomesinsights/amgen_jigsaw_external/issues/200

**Comment by markdanese** [comment]
FWIW, Naively, rows 3 and 4 should NOT be counted as two different occurrences.  Also, the behavior should not be different in the two situations above -- that seems very confusing.  

Do we have a dedup parameter for this one to control the behavior? That would solve on part of the issue, but not the second part.

**Comment by jenniferduryea** [comment]
Created #161 for your comment above @markdanese so we can take the discussion off of this thread.

**Comment by jenniferduryea** [comment]
At my request, Elizabeth gave me two other patients that I can evaluate.  And I think our logic is incorrect.  I reviewed the SQL produced and the results from the 3 patients Elizabeth found (along with the scenarios I looked at for patient 2 on synpuf_250) and have identified what we are doing (I think).

Our current logic is to take all events within a defined time interval (i.e. within 90 days) and pull those events out as events of interest.  We then apply a counter to those events of interest.  Then we pull out the events that have a counter result greater than the occurrence value listed (i.e. occurrence = 2).  This produces incorrect results.  To illustrate this, I'll use the patient data from the subject of this ticket:

| num | source_value | end_date | +60 days | Expected Output | Actual Output | in 60d window | qualify date | counter |
| -- | -------------- | ---------- | ----------- | ------------------ | ------------- | -- | ---------- | -- | 
|1| 355.8 | 10/4/2008 | 12/3/2008 | | | n | | | 
|2| 401.0 | 10/8/2008 | 12/7/2008 | | | y | 10/4/08 | 1 | 
|3| 401.9 | 3/30/2009 | 5/29/2009 | | | n | | | 
|4| 401.9 | 3/30/2009 | 5/29/2009 | | | n | | | 
|5| 401.9 | 4/12/2009 | 6/11/2009 | | | y | 3/30/09 | 2 | 
|6| 401.9 | 4/15/2009 | 6/14/2009 | | | y | 3/30/09 | 3 | 
|7| 250.00 | 5/11/2009 | 7/10/2009 | x | x | y | 3/30/09 | 4 | 
|8| 250.00 | 5/16/2009 | 7/15/2009 | x | x | y | 3/30/09 | 5 | 
|9| 401.9 | 5/16/2009 | 7/15/2009 | x | x | y | 3/30/09 | 6 | 
|10| 401.9 | 6/23/2009 | 8/22/2009 | x | x | y | 3/30/09 | 7 | 
|11| 401.9 | 7/31/2009 | 9/29/2009 | x | x | y | 6/23/09 | 8 | 
|12| 250.00 | 7/31/2009 | 9/29/2009 | x | x | y | 6/23/09 | 9 | 
|13| 780.93 | 12/6/2009 | 2/4/2010 | | |n | | | 
|14| 459.81 | 1/23/2010 | 3/24/2010 | | x | y | 12/6/09 | 10 | 
|15| 401.9 | 2/23/2010 | 4/24/2010 | | x | y | 1/23/10 | 11 | 
|16| 401.9 | 2/23/2010 | 4/24/2010 | | x | y | 1/23/10 | 12 | 
|17| 401.9 | 6/26/2010 | 8/25/2010 | | |n | | | 

What we need to do is count up the rows at the time of evaluating what events are within a 60 day time interval.  

As I'm writing this, I think I'm off by one because we are using an AFTER operator, so the first event (10/4/08) should be ignored and the counter should start at "1" starting with 4/12/09.  But, I'm more illustrating the logic to make sure I understand what is going on.  This seems to follow all of the use cases I have looked at.  thoughts?

**Comment by jenniferduryea** [comment]
As background on this ticket, the purpose of this algorithm is to find the the 4th occurrence of an event (where the event = a list of icd9 codes of interest for a patient) within 60 days of each other.  I have included a powerpoint to explain what this algorithm is trying to do and why you set occurrences=2 when you are looking for the 4th event.  Be aware that the powerpoint uses the same algorithm but is looking for the 3rd diagnosis within a 90 day period.

[AFTER Operator Bug for Github.pptx](https://github.com/outcomesinsights/conceptql/files/1776880/AFTER.Operator.Bug.for.Github.pptx)

Ultimately what we want the algorithm to do is evaluate each row of interest and capture all of the rows dated 60 days after the evaluating row (using the row's end date) and capture those rows of interest.  Then use a counter (starting with the evaluating row that you are adding 60 days to as "1") to count the rows that are within the 60 days.  The algorithm should return the patient's fourth row and any rows after that fourth row within the 60 day interval.

60 day intervals by patient:

| Patient A | Patient B | Patient C | 
| ----------------------- | --------------------- | ------------------- | 
| 1----2----3 | 1----2----3----4 | 1----2----3----4-----5 | 
| 1---- | 1----2-- | 1---- | 

In the above timeline illustration, for the first set of 60 day intervals (i.e. row 1) no events should return for Patient A, event 4 should return for patient B, and events 4 and 5 should return for patient C.  For the second set of 60 day intervals, no events should return for any patients.

What I see happening is Conceptql is identifying all of the rows within 60 days of an evaluating row.  Then a counter is applied to all of the identified rows, regardless of whether the row was the fourth row within a 60 day window or not.  So in the example above, person B will return event 2 from row 2 because the counter will continue to count any events that are within any 60 day interval.

**Comment by jenniferduryea** [comment]
Closing this out in favor of #165
