### ISSUE TITLE
SQL bug causing failed exports when using Visit Occurrence operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#174]
I used the following algorithm in a protocol, which created an Impala error
`ERROR -- : Impala::Protocol::Beeswax::BeeswaxException: AnalysisException: duplicated inline view column alias: 'place_of_service_concept_id' in inline view 't1'`

The algorithm was finding all of the visit_occurrence records with a place of service = 21.  This was supposed to represent "any hospitalization".  

Conceptql:
[["time_window",["place_of_service_filter","21",["visit_occurrence"]],{"start":"-14d","end":"-14d"}]]

![image](https://user-images.githubusercontent.com/7853238/40451909-fe8e2d9a-5e94-11e8-8d8a-2a0641171dcc.png)

Tagging @aguynamedryan for help.

**Comment by aguynamedryan** [comment]
@jenniferduryea, should we use the `visit_source_concept_id` column instead?

**Comment by jenniferduryea** [comment]
@aguynamedryan yes

**Comment by jenniferduryea** [comment]
Looks great. Studies are running to completion and results look good. Closing.
