### ISSUE TITLE
Incompatible string types in protocols with multiple index algorithms

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#179]
The following export failed with this error:
`AnalysisException: Incompatible return types 'STRING' and 'BIGINT' of exprs 't1.uuid' and 't1.provenance_type'.: CREATE TABLE `jigsaw_temp`.`jtemp1feg8m5_index_dates` STORED AS parquet AS SELECT *
FROM...`

The export_id is c0ee41fe-bf24-4a22-b342-5af51f75b991.  A test was created "mm_string_type_test_2_index_no_rev_code".  

Tagging @aguynamedryan for help.  This study failed on Sandbox.  This test recreates the error locally.

---
Moved from outcomesinsights/t_shank#100
/cc @jenniferduryea @aguynamedryan

**Comment by jenniferduryea** [comment]
This is fixed internally. Looks good.  Closing.
