### ISSUE TITLE
Populate the Vocabularies column in the algorithm repository list screen

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#181]
Currently we have a column in the algorithm repository list screen for "Vocabularies".  But, this column is not populated.  We need to populate this column with the list of vocabularies used in that algorithm.

Tagging @aguynamedryan for help and scheduling this for Broom.

**Comment by jenniferduryea** [comment]
didnt make it to broom.  Moving to v2.

**Comment by aguynamedryan** [comment]
needs #92

**Comment by jenniferduryea** [comment]
@marc-outins did this via https://github.com/outcomesinsights/jigsaw-diagram-editor/issues/723.  Closing under 18.06.03
