### ISSUE TITLE
Incorrect warning sign on the Drug Text String operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#184]
A warning sign shows up when users add words to the Drug Text String operator is used.  Please see screenshot below for the Drug Text String operator:

![image](https://user-images.githubusercontent.com/7853238/43169577-75429f92-8f56-11e8-9d16-be44bb50c3be.png)

The latest documentation for how the Drug Text String operator works: From a comma delimited list of terms, Jigsaw will search for those terms in the drug_source_value field to mimic current Amgen queries to the native data. Source values cannot contain commas and the text terms will be searched as is (including white space).

Assigning this to @aguynamedryan for help.

**Comment by aguynamedryan** [comment]
Is this issue a subset of #185?

**Comment by aguynamedryan** [comment]
This is a subset of #185 and will be fixed by #185

needs #185

**Comment by jenniferduryea** [comment]
confirmed question mark icon is removed for drugtextstring operator.

![image](https://user-images.githubusercontent.com/7853238/93513752-27f33d00-f8db-11ea-8c7e-cc5d255543c0.png)
