### ISSUE TITLE
Discussion: Prevent lexicon from validating codes against certain selection operators

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#185]
Related to #184, it looks like Lexicon is validating codes against all selection operators.  Normally that works great for core selection operators, like icd9, icd10, hcpcs, cpt.  But, Amgen has a number of custom selection operators (i.e. JMDC procedure, LPD_Australia, TST_ID, etc) that Lexicon does not have codes for.  So Lexicon will through up errors for all codes placed in these custom vocabularies because Outins does not have access to these data source-specific vocabularies.  

This is similar to the Drug Text operator in that users are searching for drug names (string text) in this operator.  Lexicon will need to have the strings for every drug available - which seems unlikely to ever happen.  So the Drug Text operator will have a warning for an "unknown code" for every text string listed in that operator.

I propose we build a way to shield certain operators from being validated against Lexicon so that codes in these operators do not get invalid warnings (i.e. "unknown code" warnings).

Tagging @markdanese @aguynamedryan @marc-outins for discussion.

**Comment by aguynamedryan** [comment]
We could make it so that if there is no entry for the vocab in Lexicon's vocabularies table, we don't check for unknown codes?  We could probably take it a step further and if the concepts table has _no_ entries for a given concepts.vocabulary_id, we don't check for unknown codes.

**Comment by jenniferduryea** [comment]
@aguynamedryan that sounds reasonable to me.  Removing question label.

**Comment by jenniferduryea** [comment]
confirming the question mark icon is removed for Drug Text String operator and CPT/HCPCS operator.  See screenshot below.
![image](https://user-images.githubusercontent.com/7853238/93513661-072ae780-f8db-11ea-9218-e381e2381e20.png)

I'm not sure where else to test this, but this looks good to me.
