### ISSUE TITLE
Scope data type for additional columns drug_days_supply and drug_quantity are incorrect

### ISSUE THREAD

**Issue by marc-outins** [outcomesinsights/conceptql#187]
The data type for drug_days_supply is set to Float which causes errors down stream when using that column to do date math since Impala requires an integer to add days to a date.  

This causes errors when running sentinel drug and medication event rate studies that includes an index event that does not just select from the drug_exposure table (drug_exposure.days_supply is set to be an integer).

The data type for drug_quantity is set to BigInt but drug_exposure.quantity is set to float so we should update drug_quantity to be the same.  This has not caused any problems as far as I know.

**Comment by jenniferduryea** [comment]
This issue was reported TO amgen under this ticket https://github.com/outcomesinsights/amgen_jigsaw_external/issues/221

**Comment by jenniferduryea** [comment]
ran on sandbox and correct results come out.  Closing.
