### ISSUE TITLE
Support ProviderFilter Under OMOPv4.5+

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#190]
It looks like the underlying ProviderQueryModifier for OMOPv4.5+ was never properly implemented.  The class is almost identical to that used for GDM support.

In OMOPv4.5+ need to be able to find provider_ids from any type of table that has some sort of provider ID column.

**Comment by jenniferduryea** [comment]
I tested the following JSON code against amgen's RWD Impala (against full marketscan msccae_mdcr) and the code completed with results.

`
[
  "provider_filter",
  [
    "icd9",
    "412"
  ],
  {
    "specialties": "38004458"
  }
]`

Since it returned results on Amgen's data, this looks good to me.
