### ISSUE TITLE
When using scope-level windows, all joins of results should occur within the same window

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#193]
#123 introduced scope-level windows, a feature we leverage a lot in TShank.

This feature limits each selection operator to only pull results that fall inside of the window provided for each person and works just fine if only a single window exists per person.  If a person has more than one window, we run into issues.

If a person has more than one window, the selection operators pool together the results that fall in either window.  Downstream operators consider all of these results, without paying attention to which window a set of results originally came from.

For instance, say a person has two scope-level windows (A, and B).  And say there is a ConceptQL statement like this: 
```
[ "after", { left: ["icd9", "412"], right: ["cpt", "99214"] } ]
```

which is our classic "all 412s that happen after an occurrence of 99214.

The expected behavior would be that if ConceptQLs find a 99214 _only_ in window A, but 412s _only_ in window B, there should be no results because during window A the criteria of a 412 occurring after a 99214 was never met.

However, because downstream operators do not limit their search of results to a single window, currently ConceptQL will pass the 412s from window B on through because it does not know to limit its comparison to window A since 99214 was only found in window A.

I suspect this bug has a huge impact on recurrent event studies.

The description of this issue is hard.  The solution seems fairly straightforward -- make all operators aware of windows of time and only allow comparison of results that share the same window.

Implementing this solution is going to require changing the behavior of almost all temporal and other comparison operators.  We're at a bit of a disadvantage as well because none of our sample data contains patients with multiple observation periods, nor, at the moment, do any of our tests against sample data have the means to apply scope-level windows.  So making this change at this point is a bit worrisome as our test coverage in this area isn't as strong as in other places.

At the moment I'm considering two options:

- Append a window id onto the end of a person_id so that all operators that are simply joining on person_id will now be tricked into joining by person_id and window id
  - The code to make this modification is all in one place and would be the most easy to change
  - There are some selection operators that don't use windows (think demographic operators like gender) and so they would not carry around the modified person_id without somehow being modified
  - The person_id would need to be stripped of its window suffix at the end of the statement before the final results are returned
  - Temp tables would be much harder to debug because the window id would be used throughout the evaluation of a ConceptQL statement, but would ultimately not end up anywhere where we could see/debug it.
- Add a window_id column to the result set
  - Again, the majority of the code that would need to consider this column is all in one place
  - But, again, there are some operators that would need individual modification to take this new column into account
  - Leaving in this additional column would be less dangerous and operators that still only generate or join against a person_id would be fine

Also, a few operators behave strangely if they are required to consider multiple windows per person when processing sets of results

For instance, if a person has a set of results from window A and a set of results from window B, what does the `First` operator do with those results?  If the `First` operator occurs at the end of the ConceptQL statement, it seems clear to choose the very first result, regardless of window.  But, if the `First` operator occurs in the middle of a ConceptQL statement, it might be important to continue evaluating the first result from each window for that person.

Long story short, this bug represents a technical and philosophical challenge to resolve.  However, as it stands, ConceptQL does not behave as expected and we need to resolve this issue somehow.  Before moving forward though I think we need to resolve some of the following issues:

- Better test coverage of scope-level windows -- even if the behavior is wrong at the moment, it would be nice to pin down how ConceptQL behaves so as we change behavior our tests can demonstrate how results change
- Better tracking of which columns each operator supplies
  - This is mostly a note for me, but ConceptQL's internals could use a solid API for tracking what columns are avaiable from upstream operators.  It would make it much easier for us to fix this issue
- Discussion about occurrence and 1in2out and perhaps other operators and how they should behave when scope-level windows are applied

**Comment by aguynamedryan** [comment]
Observation periods are truncated using the `TrimDateStart` and `TrimDateEnd` operators.

**Comment by markdanese** [comment]
I like the window id column.  That makes a lot of sense to me.

> For instance, if a person has a set of results from window A and a set of results from window B, what does the First operator do with those results? If the First operator occurs at the end of the ConceptQL statement, it seems clear to choose the very first result, regardless of window. But, if the First operator occurs in the middle of a ConceptQL statement, it might be important to continue evaluating the first result from each window for that person.

I am thinking of this as truncating the data.  So the question doesn't seem to be necessary (unless I am thinking about this incorrectly).  We just restrict everything to the window where the index date resides.  Nothing else exists.  At some point we might want to consider a modification that includes all windows before the index date for inclusion and exclusion criteria.  But I am trying to keep it simple for now.

Obviously, we can discuss this in much more detail.

**Comment by aguynamedryan** [comment]
I agree about the window id column.

> We just restrict everything to the window where the index date resides. 

In recurrent event studies, we have many potential index dates and windows in which to evaluate those index dates.

**Comment by jenniferduryea** [comment]
created multiple_scope_window_test for testing framework.  

For greater clarity on the problem, this only affects studies that have algorithms that require temporal relationships between events to return the correct event.  For example, this would be needed for an algorithm that is looking for an event that happened after/before another event.  The test above was created as a recurrent study where two index events were considered (and baseline timelines did not overlap between the two index dates) and data from these two baselines were pooled together to find a qualified inclusion event (i.e. inclusion was the second icd9 code).  This is a pretty rare occurrence.  But still a big bug to fix.

**Comment by jenniferduryea** [comment]
I believe this is working as described.
