### ISSUE TITLE
New operator: Hospitalizations

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#194]
This is based on the brain-dump emailed on 9/13/18 "Re: GDM operators for generic events".

Use case: time to first hospitalization
Definition:  will be defined using facility claims only

Proposal:  one ConceptQL operator that:
- GDM compatibility
  - presence of an admission record (GDM)
  - Will need to check for associated context record by source_type_concept_id inp and/or snf
- OMOP v4.5+
  - use visit_occurrence.place_of_service_concept_id = "inpatient"

Tagging @markdanese for refinement (if any) and @aguynamedryan for implementation.  Scheduling for Chisel.

**Comment by markdanese** [comment]
Output:  Length of stay, discharge status, admission source, primary diagnosis code, primary diagnosis vocabulary, admit date, discharge date

SNF will be decided by however SNF is mapped to core concepts (inpatient, outpatient, physician)

**Comment by aguynamedryan** [comment]
Here is my understanding of this operator.

### Logic for GDM

- Look for `collections` records
  - `collections` record must have
    - associated `admission_details` record
    - `collections.collection_type_concept_id` is mapped to "inpatient" or "snf"

### Logic for OMOPv4.5+

- `visit_occurrence` records
  - `visit_occurrence.place_of_service_concept_id` = any "inpatient" type concept

## Output

Desired output columns:

- Length of stay
- Admission source
- Discharge status
- Primary diagnosis code
- Primary diagnosis vocabulary
- Admit date
- Discharge date


### Columns used for output in GDM

- Need the following records to assemble those columns:
  - `admission_details` as `collections.admission_details`
  - `primary_clinical_code` as `collections.clinical_codes.provenance_concept_id` = "primary"
- Length of stay
  - (`admission_details.discharge_date` - `admission_details.admission_date`) + 1
- Admission source
  - `admission_details.admit_source_concept_id.concept_text`
- Discharge status
  - `admission_details.discharge_location_concept_id.concept_text`
- Primary diagnosis code
  - `primary_clinical_code.clincal_code_concept.concept_code`
- Primary diagnosis vocabulary
  - `primary_clinical_code.clincal_code_concept.vocabulary_id`
- Admit date
  - `admission_details.admission_date`
- Discharge date
  - `admission_details.discharge_date`

### Columns used for output in OMOPv4.5+

- Length of stay
  - (`visit_occurrence.visit_end_date` - `visit_occurrence.visit_start_date`)
- Admission source
  - NULL
- Discharge status
  - NULL
- Primary diagnosis code
  - NULL
- Primary diagnosis vocabulary
  - NULL
- Admit date
  - `visit_occurrence.visit_start_date`
- Discharge date
  - `visit_occurrence.visit_end_date`

**Comment by jenniferduryea** [comment]
Yup.  Sounds good to me.

**Comment by markdanese** [comment]
For GDM, shouldn't the mapping table determine whether SNF is inpatient or not?  Not the operator itself?  In theory, someone could want hospital, SNF, or both.

**Comment by jenniferduryea** [comment]
to clarify, @aguynamedryan is using the mapping table in GDM to find all concepts that match "inpatient" and "snf".  I guess the real question here is, do you want the "hospitalization" operator to return inpatient and snf admissions?  this is analogous to searching the entire medpar file for an inpatient hospitalization.  If you don't, then the operator should only return concepts mapped to "inpatient" only.  This is analogous to picking out medpar records without a snf type.

My point of view - we should only be using "inpatient" concepts for the hospitalization records.  This better translates across all types of data - commercial and medicare.  I do understand that we have in the past used any record in the medpar file as a "hospitalization".  And, in some sense, a SNF admission happens in a hospital.  But, I believe when people talk about "hospitalization", they are talking about acute conditions being cared for in a hospital using the DRG system.  And if you really want SNF records, you can use the other operator (specified here: dhttps://github.com/outcomesinsights/conceptql/issues/198).  

I'm open to other thoughts on this.

**Comment by markdanese** [comment]
GDM uses the mappings table, using the "inpatient" type

**Comment by aguynamedryan** [comment]
I'd like to propose that we "reuse" some existing ConceptQL column names for the output columns for hospitalization:

| output column originally agreed to | equivalent conceptql column we could use instead |
| ----- | ------ |
| admission_date | start_date |
| discharge_date | end_date |
| primary_diagnosis_code | source_value |
| primary_diagnosis_code_vocabulary_id | source_vocabulary_id |

The following columns would still be added to the result set since they don't have an pre-existing equivalent:

- admission_source
- discharge_location
- length_of_stay

**Comment by markdanese** [comment]
The dictionary can clarify that start_date = admission date, etc.

**Comment by aguynamedryan** [comment]
Ooooooh.  Good point!  Great, thanks!

**Comment by marc-outins** [comment]
@aguynamedryan We should be looking at contexts.source_type_concept_id for file type information, not collections.collection_type_concept_id.

**Comment by jenniferduryea** [comment]
sending back to programming. I tested the sql generated in the JAM (source view) for the algorithm below and the SQL uses the provenance_concept_id = 100012440, which is related to "primary".  The pasted code did not bring up any results.  We need this to look up the concept_id related to "inpatient".  

The algorithm was made under outins.jsaw.io (http://outins.jsaw.io/algorithms/74d3835b-2d16-46f9-9502-2606bd612210).

![image](https://user-images.githubusercontent.com/7853238/54775568-83038100-4bcb-11e9-95a8-cbe542784ccd.png)

**Comment by jenniferduryea** [comment]
checked this against gdm version of seer medicare (esophageal).  Used hospitalization as an operator on it's own as index, inclusion, and outcome.  I also used the operator in an AFTER arm to ensure conceptql events were being generated properly.  Works as expected.
