### ISSUE TITLE
New operator: Office Visits

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#195]
This is based on the brain-dump emailed on 9/13/18 "Re: GDM operators for generic events".

Use case:  number of office visits after index
Definition:  
- Can be defined only from physician claims - no facility claims
   - There may be some facility claims from office visits where physician is renting out space from hospital.  Will have POS=22 on physician claim
   - Facility claim will have the same E/M cpt code
- Find all E/M (“Evaluation and Management” CPTs) codes will get all face-to-face meetings with physician in both Physician and Facility claims
   - Will not include: flu shot (immunization only) visits, or any other visit where the patient did not see a doc
- Payers define "office visit" E/M code and only apply "office visit" copays/coins to this code

Proposal:  one ConceptQL operator that:
- Defines E/M codes as an "office visit" and is found in any file/table/domain
   - use cpt = 99201-99215, 99241-99255 ( as reference: https://www.supercoder.com/cpt-codes-range/2869)
   - GDM - only look for cpt/hcpcs codes in clinical_codes table
   - OMOP v4.5+ - look for cpt/hcpcs codes in procedure_occurrence table
 

Tagging @markdanese for refinement (if any) and @aguynamedryan for implementation.  Scheduling for Chisel.

**Comment by aguynamedryan** [comment]
@jenniferduryea, @markdanese: this is something that can be accomplished with ConceptQL already and does not need to be a new operator, correct?

**Comment by markdanese** [comment]
I believe so.  This should be an algorithm, not an operator.

**Comment by jenniferduryea** [comment]
final algorithm is added into outins.jsaw.io under http://outins.jsaw.io/algorithms/e0dcea84-117d-4400-8b95-7ae539729a2a.  Mark this as completed.
