### ISSUE TITLE
New operator: ER Visits

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#196]
This is based on the brain-dump emailed on 9/13/18 "Re: GDM operators for generic events".

Use case:  number of ER visits/use after index
Definition:  
-  Will be defined using facility claims
- As background, Truven uses place of service, provider type (with service type), and procedure type (all truven generated variables besides POS) to find er visits.  We will use revenue codes.  Not sure of the sensitivity/specificity/ppv

Proposal:  one ConceptQL operator that:
- Find all revenue codes 045x (for reference: https://med.noridianmedicare.com/web/jea/topics/claim-submission/revenue-codes)
   - This will allow Jigsaw to look at both inpatient (admitted patients) and outpatient facility (never admitted patients) bills for ER use
   - GDM - only look for revenue codes in clinical_codes table
   - OMOP v4.5+ - look for revenue codes in procedure_cost table and report associated procedure_occurrence record
 

Tagging @markdanese for refinement (if any) and @aguynamedryan for implementation.  Scheduling for Chisel.

**Comment by jenniferduryea** [comment]
Looking at the Venkatesh 2017 (https://onlinelibrary.wiley.com/doi/full/10.1111/acem.13140) article, there are four algorithms they used to define ER visits:

1. HCPCS codes 99281, 99282, 99283, 99284, and 99285 in physician claims
1. Revenue codes 0450–0459, 0981 in facility claims
1. ResDac definition: algo 2 but also look for >$0 amount under "emergency department costs" in MEDPAR
1. Yale definition: used each line (i.e. revenue code on facility claim) as a possible "visit".  Used algo 1 but filtered by place_of_service = 23 for all hcpcs and added hcpcs 99291 with pos filter; used algo 2; also included hospital observation lines as possible ER visit (revenue code 0762, 0760 with HCPCS G0378) only if claim (i.e. collection) included the revenue codes used in algo 2.  Also, if facility claim lines overlapped with professional claim lines by +/- 2 days, the facility claim line was not considered a separate ER visit.

The study did not do a sensitivity/specificity analysis because there was no gold standard.  They did compare results of all 4 algos against each other to show how much is overlapped and how much was not.

Some options we should consider:
1. We can make conceptql algorithms for algo 1 and 2.  
1. Algo 3 is a problem for SEER Medicare since they use the MEDPAR file.  This file does not include revenue codes but rolled up variables like "charges for emergency services" which adds all of the charges with revenue codes 045x.  We are currently not putting that info into GDM.  I'm not sure where to put that.
1. Algo 4 is a problem just based on the +/- 2 day overlap.  I'm not sure how to do that in conceptql (there may be a way but it slips my mind now).  But we can do everything else.

Do we want to even consider making these algos since there are no sens/spec stats on the performance of these algos?

**Comment by markdanese** [comment]
I don't know of a better way to do ED visits.  We could look for other algorithms, but I think having as many of these as possible is a good way to go.

Definitely do 1 and 2 and 4.  Algo 3 is interesting.  We will have to talk about whether/where that goes in GDM.  Particularly since it comes from RESDAC.

**Comment by markdanese** [comment]
We should also consider whether "admission source" of ED is in the data and is relevant to any of the above definitions.  Just mentioning it because we have used it in HCUP data.

**Comment by markdanese** [comment]
It looks like 2, 3, and 4 are more consistent.  The provider only definition seems to miss a lot of events that the others include (n=957,784).  Hard to know whether these are predominately false positives or false negatives.  
<img width="709" alt="screenshot" src="https://user-images.githubusercontent.com/7732537/49962551-5b18c900-feca-11e8-8d41-4307ecd7b3ed.png">

**Comment by jenniferduryea** [comment]
@markdanese I do know that admission source was NOT used in the Venkatesh 2017 paper.  But we do have it in SEER and LDS Medicare data.  That can be a separate ER visit algo (and I'm assuming we need to find a published algo that uses that field)?

**Comment by markdanese** [comment]
I think it would be a slight modification to the facility definition.  Maybe it is something we test in our data.  But if someone has used it, that would be useful.  I would not spend a ton of time on it, but it is worth seeing if there are any other good ED algorithm studies out there.

**Comment by jenniferduryea** [comment]
Per resdac, the use of admission source = 7 (transferred from emergency room) has been obsolete since 7/1/2010 (https://www.resdac.org/cms-data/variables/claim-source-inpatient-admission-code).  So I don't think we should be using this code to identify ER visits in our medicare data.

**Comment by markdanese** [comment]
algorithm only.  no conceptQL changes needed.

**Comment by aguynamedryan** [comment]
@jenniferduryea, if this is algorithm only, am I still needed on this ticket?

**Comment by jenniferduryea** [comment]
currently created algorithms in outins.jsaw.io:
option 4: http://outins.jsaw.io/algorithms/5fa00660-7bfd-44dd-90c2-1adf54cfca90
option 2: http://outins.jsaw.io/algorithms/f25af792-9775-4680-95aa-8fdebe9caeb1
option 1: http://outins.jsaw.io/algorithms/4accd3b1-78a2-4133-ac27-30e86f341bcc

closing.
