### ISSUE TITLE
New operator: SNF Use

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#198]
This is based on the brain-dump emailed on 9/13/18 "Re: GDM operators for generic events".

Use case:  number of snf visits after index
Definition:  
-  Will be defined using facility claims

Proposal:  one ConceptQL operator that:
- GDM compatibility
   - presence of an admission record
   - need to check associated context source_type_concept_id for "snf"
- OMOP v4.5+ - no thoughts now
 

Tagging @markdanese for refinement (if any) and @aguynamedryan for implementation.  Scheduling for Chisel.

**Comment by markdanese** [comment]
See #194 and select SNF based on mappings table

**Comment by aguynamedryan** [comment]
### Logic for GDM

- `collection_records.admission_details` is not null
- `collection_records.collection_type_concept_id` is concept mapped to "SNF" concept

### Logic for OMOPv4.5+

- Returns no records

## Output

As per Mark, output columns will be the same as defined in Hospital (#194) and will use the same sources for each column's value

**Comment by markdanese** [comment]
@marc-outins should create SNF type in mappings table for this.  Otherwise same as Hospitalization (#194)

**Comment by marc-outins** [comment]
@aguynamedryan We should be looking at contexts.source_type_concept_id for file type information, not collections.collection_type_concept_id.

**Comment by jenniferduryea** [comment]
I need data that contains snf records to test this in chisel.jsaw.io.  Removing from testing and sending back to @marc-outins for implementation.

**Comment by jenniferduryea** [comment]
checked this against gdm version of seer medicare (esophageal).  Used snf as an operator on it's own as index, inclusion, and outcome.  I also used the operator in an AFTER arm to ensure conceptql events were being generated properly.  Works as expected.
