### ISSUE TITLE
Missing/Duplicated Operators, including Revenue Code.

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#201]
On outins.jsaw.io and notice 1) Revenue Code operator is missing, and 2) there are duplicates for "UB04/CMS1450 Revenue Codes (CMS)"

![image (2).png](https://codetreeusercontent.s3.amazonaws.com/uploads/28315306-b253-495c-8e32-b48baf49659a/image+%282%29.png)

It's a bug.  One of those operators is the hard-coded revenue code operator we use for OMOP since revenue codes live in a strange place in that data model.  The other is a dynamically generated operator that only appears when GDM is used.

Since the two share a common name "Revenue Code" ConceptQL is accidentally merging their information together, making it look like we have two copies of the same operator.

I think I can safely remove the dynamically generated one and everything will be ok.

**Comment by jenniferduryea** [comment]
Updated ticket to include more than just Revenue Code operator.  We have multiples of ICD-10CM, ICD-9CM, CPT, etc.

**Comment by aguynamedryan** [comment]
So, I've overhauled the vocabulary-related operators, but we're still seeing duplicated operators because some operators now have at least two valid "names", e.g. "icd9" was or original name for what is more appropriately called "icd9cm" so ConceptQL must respond to both names.

We're going to add and "aliases" to the metadata for each operator which will contain an array of names to which the operator might also respond to. 

So, icd9cm's entry in the metadata will look something like:

```
"icd9cm" {
...
aliases: ["icd9"]
}
```
I'd advise that the JAM then create a "lookup" table that looks something like:

```
{
  "icd9cm": "icd9cm",
  "icd9": "icd9cm"
}
```

so that the JAM can look up the proper "name" for a given operator and find that operator in the supplied metadata.

**Comment by aguynamedryan** [comment]
The ConceptQL portion of this work is now ready for testing, but @marc-outins will need to make some changes to the JAM for everything to work as expected.

**Comment by aguynamedryan** [comment]
needs outcomesinsights/jigsaw-diagram-editor#830

**Comment by jenniferduryea** [comment]
Confirmed that duplicate algos are fixed.  Looks great.
