### ISSUE TITLE
person.year_of_birth is set to 2000 value is missing

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#208]
If a person has a null value for person.year_of_birth in the omop schema the value is set to the year  2000.  This is done without a warning.  I'm thinking we should set it to 0 so that it gives a ridiculous result when calculating age.

---
Moved from outcomesinsights/jigsaw#425
/cc @marc-outins @jenniferduryea @aguynamedryan

**Comment by jenniferduryea** [comment]
moving to chisel.

**Comment by markdanese** [comment]
no more omop v4 support.  no longer needed.
