### ISSUE TITLE
OneInTwoOut's Length of Stay Option Causes Failure

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#216]
The OneInTwoOut operator calls Sequel#date_sub with improper arguments, causing a failure when attempting to generate the query for this operator when the `length_of_stay` parameter is set.

This is fixed for PostgreSQL (and possibly Impala) in 59179a7dd06cba7b9e1e12b6b1b10ccb5ca9d2c6

**Comment by markdanese** [comment]
does this affect Amgen's broom?

**Comment by aguynamedryan** [comment]
Yes.

**Comment by jenniferduryea** [comment]
@aguynamedryan does this only affect GDM because it's looking at the admissions_details table (that could have missing discharge dates)?  The oneintwoout operator looks at records from the condition_occurrence table in omop v4.5+, so the bug may not affect Amgen at this time.

**Comment by jenniferduryea** [comment]
For background, this is an issue for both gdm and omop as this is set at the time of creating conceptql.  Fixed in 18.06.05
