### ISSUE TITLE
Slow "Select All" Algorithms in GDM

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#242]
Mark reports that algorithms which use the "*" (select all) feature in selection operators take a _long_ time to complete.

I made a cursory look at the code and I think the problem is that rather than searching by `clinical_code. clinical_code_vocabulary_id`, we're gathering _all_ concept_ids from a vocabulary and comparing them against `clinical_code. clinical_code_concept_id`.

Seems like a quick fix.  We just need to make sure we carry that change over to outcomesinsights/conceptql#241 

---
Moved from outcomesinsights/jigsaw-diagram-editor#819
/cc @aguynamedryan

**Comment by aguynamedryan** [comment]
I have a couple failing tests for this change and they revealed a philosophical issue.

There are at least 2 HCPCS codes in the SynPUF 250 dataset that are invalid.  We have ETL'd them so the `clinical_codes.clinical_code_concept_id` is 0

Before I changed the code, ConceptQL would compare `clinical_codes.clinical_code_concept_id` against _all_ `concepts.id` where `concepts.vocabulary_id` was HCPCS, meaning that we'd compare `clinical_codes` table against thousands of concept_ids, which was slow.  _But_ it also meant that `clinical_codes` where `clinical_code_concept_id` was 0 would be ignored, so we'd leave those two entries with invalid codes out of the result set returned as part of "select all" HCPCS.

I changed ConceptQL to now look at `clinical_code.clinical_code_vocabulary_id`, meaning we don't filter out `clinical_codes` with `clinical_code_concept_id` of 0.

There are three possible solutions to handling the difference:

1. Keep the change as is, and return "invalid" `clinical_code` records where `clinical_code_concept_id` is 0
2. Update my change to return only those `clinical_codes` where `clinical_code_concept_id` is *not* 0
3. Update our ETL to add `concepts` rows for these invalid HCPCS codes so that _all_ `clinical_codes` records have a non-zero `clinical_code_concept_id`

I _thought_ we were already doing option 3, but @marc-outins says @markdanese suggested we leave invalid codes set to 0.

Thoughts?

**Comment by aguynamedryan** [comment]
BTW, the "invalid" HCPCS codes were `99910` and `0851` which is nice because the latter is _clearly_ wrong (violates the expected format) and the former is simply not a valid code, but has the correct format.

@markdanese says go with option 2 for now.

This means that ConceptQL will have no way to find `99910` or `0851` in GDM.  We can revisit the ETL process later to see if we want to assign concept rows to things like `99910` at least.

**Comment by jenniferduryea** [comment]
tested this on chisel.jsaw.io.  Created outcomes algo with select all parameter for icd9 operator.  study ran in a couple of sections.  

Test case: patient 172 has index 1/29/08.  outcome event 305.11 11/16/09 has concept_id = 0 and did not show up in output.  Confirmed all icd9 codes from patient showed up in outcomes minus the one icd9 that had a concept_id = 0 and 6 other events that happened on the same day as index date.

couldn't test relative speed, since that was the original issue, but the study ran in seconds, instead of minutes. So I'm guessing that's a good benchmark.

Please see export_id for test case: ea309620-cf0f-4970-a998-72a1ed2c7253
