### ISSUE TITLE
Gemscript operator vocabulary_id set to NULL for queries

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#243]
When running an algorithm that contains a Gemscript operator, the SQL shows that the "vocabulary_id is NULL", instead of "vocabulary_id = 'Gemscript'".  An example export_id = 9b1899b3-4c9e-4518-8637-a53f95ad7290 that was run on outins.jsaw.io against cprd_2019_llt_shard1_20190531.  I ran the algorithm's SQL directly on the GDM data source (through pgadmin), replaced 'vocabulary_id is NULL' to 'vocabulary_id = 'Gemscript'' and I got results.

Sending this to @aguynamedryan for help.  Setting this to Chisel 02 for high priority (since we are working on a project that needs this).

**Comment by aguynamedryan** [comment]
Our Lexicon vocabularies table is missing the OMOPv4 ID for the Gemscript vocabulary and this is causing the error you're seeing.

I'm rebuilding the Lexicon tables now and will deploy a fix, probably later tonight.

**Comment by jenniferduryea** [comment]
THis has been fixed.  It 's been updated on outins.jsaw.io and it the vocabulary_id is indicated.  Closing.
