### ISSUE TITLE
Scoping windows to only consider start_date for events

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#245]
We need to change the logic of selecting events for scoping windows since we have run into issues with events that have date ranges. Currently, if the index date falls within these event's date range, the hospice/hospitalization record (for example) will not be output as baseline or followup because the event straddles the baseline/followup periods, most recently discussed in #197 .  The scoping window will remove the event from consideration because the date range is not inclusive of one period - baseline or followup.  We need to change the scoping window logic so that events that have a date range and span the patient's index are included for protocol algorithm consideration. We could then create algorithms that consider start or end date logic for date range events.

tagging @aguynamedryan for implementation.

**Comment by aguynamedryan** [comment]
Do we _always_ want to consider _only_ start_date of events?

I imagine that many of our TShank tests will have changes to their output, so would you please provide a specific test or tests (if we want to consider end_date, or date ranges) for this situation to verify that it behaves as expected.

**Comment by aguynamedryan** [comment]
I see outcomesinsights/t_shank#173 answers my question.  I will provide test cases for ConceptQL.  

Please provide test cases for the three scenarios in outcomesinsights/t_shank#173

**Comment by jenniferduryea** [comment]
done

**Comment by jenniferduryea** [comment]
additional tests are documented in https://github.com/outcomesinsights/jigsaw-diagram-editor/issues/827.  Looks good.  Closing out.
