### ISSUE TITLE
Use Billing Dates for Hospice operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#248]
After discussion with #194 and #197, it looks like users may want to query and report the events in a different way. Please see specs below. The changed areas are under output for gdm.

### Logic for GDM

- `collection_records.admission_details` is not null
- `contexts.source_type_concept_id` is concept mapped to "hospice" concept

### Logic for OMOPv4.5+

- Returns no records

## Output

Desired output columns:

- Length of stay
- Admission source
- Discharge status
- Primary diagnosis code
- Primary diagnosis vocabulary
- Admit date
- Discharge date
- billing start date
- billing end date

### Columns used for output in GDM

- Need the following records to assemble those columns:
  - `admission_details` as `collections.admission_details`
  - `primary_clinical_code` as `collections.clinical_codes.provenance_concept_id` = "primary"
- Length of stay
  - (`admission_details.discharge_date` - `admission_details.admission_date`) + 1
- Admission source
  - `admission_details.admit_source_concept_id.concept_text`
- Discharge status
  - `admission_details.discharge_location_concept_id.concept_text`
- Primary diagnosis code
  - `primary_clinical_code.clincal_code_concept.concept_code`
- Primary diagnosis vocabulary
  - `primary_clinical_code.clincal_code_concept.vocabulary_id`
- Admit date
  - `admission_details.admission_date`
- Discharge date
  - `admission_details.discharge_date`
- Billing Start date
  - `collections.start_date`
- Billing End date
  - `collections.end_date`

For output, the Billing Start and Billing End date will be specified in Jigsaw output as events.start_date and events.end_date.  Primary Code and Primary Diagnosis Vocabulary will use events.source_value and events.source_vocabulary_id.  All of the other fields will be new columns.

Additional logic is needed to fill out the events table for hospice events. The last hospice event for a patient contains the discharge date, LOS, and discharge status.  It would be nice if Jigsaw took this information from the last hospice event and back-filled these cells in all prior hospice events output in the events table.

Since we have two sets of dates (billing and admit/discharge), conceptql will use the Billing Dates for the start/end date operations.  And the Protocol Builder will use billing dates for event selection.

Tagging @aguynamedryan for implementation and @markdanese for discussion, if needed.

**Comment by aguynamedryan** [comment]
@jenniferduryea, same questions as #247, plus:

- I'm not sure how to implement the back-fill of discharge date.  How does GDM indicate that a set of hospice records are all related?

**Comment by jenniferduryea** [comment]
@aguynamedryan 
- GDM does not.  Jigsaw will link together the hospice records by admit_date, where the same admit_date = related hospice admission.

**Comment by aguynamedryan** [comment]
I've implemented the column changes similar to #247, but split out the "backfill" part into its own ticket: #254

**Comment by jenniferduryea** [comment]
since @marc-outins  is also working on hospitalization operator, might as well do this.

**Comment by jenniferduryea** [comment]
this is now fixed as of the last comment in #247 Closing.
