### ISSUE TITLE
DrugTextString operator causes algorithms to freeze in Broom 

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#249]
Amgen reported the following algorithms are causing the algorithm screens to freeze:  https://github.com/outcomesinsights/amgen_jigsaw_external/issues/260.  Confirmed this issue by copying conceptql code to an algorthim under broom.jsaw.io.  Tagging @aguynamedryan for help.

**Comment by jenniferduryea** [comment]
@aguynamedryan found a way around the bug - see GIF below.

![fix_drugtextstring](https://user-images.githubusercontent.com/7853238/61913257-61a40000-aef1-11e9-9c38-f9b9363bb957.gif)

**Comment by aguynamedryan** [comment]
Moved to outcomesinsights/jigsaw-diagram-editor#828
