### ISSUE TITLE
Jigsaw to pull lab values from custom vocabulary operators

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#253]
We need output from custom vocabulary operators to bring out lab records.  The current use case is CPRD's vocabulary "enttype".  Lab values are associated to these enttype codes (via measurement_details_id from the clinical_codes table).  This affects a whole slew of tickets: #145 #241 #184 and #185.  But, probably the easiest fix is to assign domains to custom vocabularies in GDM (described in https://github.com/outcomesinsights/generalized_data_model/issues/118) and then have lexicon read the assignment and know to pull out lab values (and also drug - since we're at it) for output.

Tagging @aguynamedryan for implementation and @marc-outins for GDM changes(?)  This is now a high priority ticket since it directly affects a project we are working on (CPRD).  Assigning to chisel 2.

**Comment by aguynamedryan** [comment]
This should be ready to go.  Thanks, @marc-outins, for updating the vocabularies file in gdm_vocabularies!

**Comment by jenniferduryea** [comment]
confirmed this works.  Please note that the values are determined by the operator you choose in the algo.  So if GDM has cpt code that has a measurement_detail_id and you use the CPT operator to query the code, the measurement_details will not be output in jigsaw because CPT operator is not defined as a "lab" operator.  But, if you use the LOINC operator, the measurement_details will be output because the LOINC operator is defined as a "lab" operator.  Tested on gdm_250_extended_20190708 and pending test for framework.  Also adding note for documentation in the diagram editor manual.  Closed.
