### ISSUE TITLE
Jigsaw to pull clinical code quantity field for drug records

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#255]
For GDM databases, conceptql pulls the days_supply field from the drug_exposure table when finding drug records and then outputs the value as "quantity" in events.  Conceptql needs to pull the clinical_code.quantity field for drug records.

Tagging @marc-outins for implementation.

**Comment by marc-outins** [comment]
@jenniferduryea ready to test.  Apparently I fixed this 3 months ago and forgot to tell everyone! fd34697e03ccf7a6bffe9c66329fb1f42b79792f

**Comment by jenniferduryea** [comment]
Tested and works!  Quantity is being reported.  Test export_id 106a26e4-1363-473f-8fe8-40d525f426f7
