### ISSUE TITLE
uuid always set to null for episode operator

### ISSUE THREAD

**Issue by marc-outins** [outcomesinsights/conceptql#260]
When the uuid option is specified it generates a unique uuid from concatenating the person_id, criterion_id, criterion_table, criterion_domain, and start_date columns.  The episode operator contains null values for criterion_id, criterion_domain, and criterion_table and concatenating a null value with anything else returns null so the uuid is always null for episode events.  This causes events to not be returned when running exports in t_shank when the episode operator is used as the index event because we do comparisons on the uuid column where we aren't expecting nulls

I tested code that force fills criterion_id, criterion_table, and criterion_domain with values within the episode operator code and was able to return results with t_shank that previously weren't returned.  Not sure if we want to do that to fix it or update the uuid generation code to be aware of which columns it should use based on the operator.

**Comment by jenniferduryea** [comment]
For the user experience, when an algorithm with an episode operator is used in a protocol, n=0 for all cohorts.  So right now, users cannot use the episode operator for protocols.  This is a high priority since we have a couple of ongoing projects that use the episode operator.

**Comment by marc-outins** [comment]
Per discussions that took place on slack (jigsaw_build) on 2019-10-15 we will do the following:

1. Add end_date to uuid_items in rdmbs/generic.rb
2. For episode operator set criterion_id = 0 and criterion_table and criterion_domain = "episode"

**Comment by marc-outins** [comment]
@jenniferduryea ready to test on chisel.jsaw.io

**Comment by jenniferduryea** [comment]
tested and passed.
