### ISSUE TITLE
DuckDB Compatibility?

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#275]
Over the last couple of years, our data pipelines have migrated to Parquet-formatted data.  [DuckDB](https://duckdb.org/) is a database engine designed to work with Parquet.  It looks like it is serverless, meaning that it is a set of libraries designed to be included in a program that will interact with Parquet files through the DuckDB libraries.

We'd need [bindings for DuckDB in Ruby](https://github.com/suketa/ruby-duckdb) and possibly a new adapter in [Sequel](https://github.com/suketa/ruby-duckdb).  It's also not clear what kind of [SQL syntax DuckDB supports](https://duckdb.org/docs/sql/introduction.html) but it looks like they heavily borrow training materials and some syntax diagrams from PostgreSQL, so that might be promising.

DuckDB aims to be fast at OLAP/aggregation-type queries, which is what Parquet designed to excel at.  The performance we get for our style of queries may not be that great, but it might be worth a try.

It is possible that we could try to run a set of PostgreSQL-based queries from an Export against DuckDB and see a) if it works and b) if it is fast

**Comment by aguynamedryan** [comment]
I was able to get the [Ruby bindings for DuckDB](https://github.com/suketa/ruby-duckdb) working.

I took an example export from our production database and ran it on a tiny shard of the data in Parquet format.  Everything went smoothly until it reached the point where it was creating the `cohort` table which involves a considerable number of `LEFT JOIN`s and it's just hung there.  Not very promising.

**Comment by aguynamedryan** [comment]
Oh, and for what it's worth, I had to make _very_ minimal changes to the queries, so DuckDB does seem to use a syntax similar to PostgreSQL and the seems to support window functions and the majority of features we use in ConceptQL.  If it weren't for this `LEFT JOIN` issue, I'd consider doing further testing.

**Comment by aguynamedryan** [comment]
Update: we're past 6 hours and still hasn't finished

**Comment by markdanese** [comment]
Left joins are the bread and butter of RDMBS.  I wonder if there is a syntax incompatibility or something simple that is wrong.
