### ISSUE TITLE
Include Label in ConceptQL Results

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#280]
@markdanese has long-wanted some way to understand where, in a particular ConceptQL statement, an event came from.  Perhaps we should include any labels on a ConceptQL operator as part of its results.

Here's how it will work:

- If there are no labels in the ConceptQL statement, the label column will be completely NULL
- If an operator has a label on it, all results from that operator will have the text of the label included in the label column of the results
- If operator A has a label and its results are processed by operator B, which also has a label, B's label will replace A's label in the results

This can act as a kind of poor-man's mapping and help store some analysis logic.

**Comment by aguynamedryan** [comment]
Adding the "label" column represents a new kind of data for ConceptQL's results -- metadata.  Up until now, ConceptQL's results are limited to only information derived from the claims data set.  Labels represent information derived from the ConceptQL statement itself.  It is not proper claims data.

This will have an impact on the behavior of Set Operators, particularly, Except and Intersect.  Both of these currently use the RDBMS's in-built operations of `EXCEPT` and `INTERSECT`.  Including labels will add some wrinkles because if operator A and operator B have identical result sets other than their labels, Intersect would consider them entirely different results.  Same with Except.

I'm going to propose that we re-work Except and Intersect so they operate on all columns _except_ label.

**Comment by aguynamedryan** [comment]
> One use case for labels might be in comorbidity algorithms where the label can store the weight.

ConceptQL already has minimal support for numeric columns, we have just never had the use cases to justify building them out.

**Comment by markdanese** [comment]
> ConceptQL already has minimal support for numeric columns, we have just never had the use cases to justify building them out.

Just to be clear, this would be for an external weight that is not part of the data but is part of the scoring for the algorithm.    As I think about it more, it is probably better thought of as meta-data and maybe belongs in the algorithm information and not the algorithm diagram.

**Comment by aguynamedryan** [comment]
@markdanese and I discussed this issue in length.

There are a couple of points we considered.

- Are labels comments?
  - Our answer is that yes, they were supposed to be, but they have already been co-opted by the Recall operator
- Will we want to manipulate/concat/etc labels via explicit operators?
  - We don't have any use cases for this

We see three options for changes:

1. Just make modification as discussed above, where labels are included in output of ConceptQL
2. Change existing labels to comments, have comments _and_ labels for all operators
3. Change label to comment, create explicit label operator, create explicit define operator for Recall

Our current implementation of Recall causes us to carry a lot of technical debt surrounding how labels are currently implemented.  The JAM probably has a lot of code surrounding how to handle labels and make them available to the Recall operator.  There is some code in conceptql as well that handles recall operators and labels that would need to be updated.  While it would be nice to ignore these issues, they were a factor in our decision.

Option 1 avoids any of this technical debt, addresses the use cases we have _currently_ and probably won't introduce too much additional technical debt should we want to implement option 2 or 3.

**Comment by aguynamedryan** [comment]
Option 1 has been implemented.
