### ISSUE TITLE
Remove Source_to_concept_map (SCM) check for operators

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#46]
I am running into issues where users are adding in comma-separated codes into selector operators and the JAM is generating errors within the cards - basically showing that the codes entered are an "invalid source code".  An example is below:
![image](https://cloud.githubusercontent.com/assets/7853238/16322007/1cd3ae36-3955-11e6-9269-bb8adc316d85.png)

These errors are coming up because codes are not found the SCM.  Since ConceptQL is now working on a different version of the CDM where using the SCM for queries are not needed, we need the JAM to stop checking against the SCM for invalid codes.

Note that this issue was originally posted in the jigsaw-diagram-editor repo (https://github.com/outcomesinsights/jigsaw-diagram-editor/issues/155)

**Comment by aguynamedryan** [comment]
I think the warnings are useful, assuming the vocabularies are complete.  I think the real solution is to ship ConceptQL with a more comprehensive set of vocabularies.

Marking this as wontfix in favor of #51.
