### ISSUE TITLE
Support a Place_of_Service filter operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#54]
Create a filter in ConceptQL that will pass all streams through a place_of_service operator where those records have a visit_occurrence record with the visit_source_concept_id (or place_of_service_source_value?) equal to what is indicated in the filter.

**Comment by aguynamedryan** [comment]
@jenniferduryea, based on your experience, how would you like to specify places of service?

I'm thinking the operator should support:
* OHDSI vocab 24 (the rollup)
* ODHSI vocab 14 (CMS PoS)

* What other kinds of place of service might we want?
  * Facility type?

**Comment by aguynamedryan** [comment]
If a result doesn't have a place of service information (e.g. it's a person record) should we pass it through or drop it?

**Comment by jenniferduryea** [comment]
I believe we agreed to not pass through information that does not have pos info.  So if you are looking for pos=23 in a person stream, no records will result.

**Comment by marc-outins** [comment]
Confirmed the pos filter is working
