### ISSUE TITLE
Support a Co-Reported operator

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#56]
ConceptQL needs to support a "Co-Reported" operator that will take multiple upstreams and pass through events when events from each stream occur in the same visit_occurrence or context?/collection?

**Comment by aguynamedryan** [comment]
If a result doesn't have a corresponding visit_occurrence_id or context_id, should we pass it through, or remove it?

**Comment by jenniferduryea** [comment]
Is this done per NCI demo?

**Comment by jenniferduryea** [comment]
this was only done for OI_CDM.  This needs to be done for OMOPv4.5_plus.  Sending this back to Jarlsberg.

**Comment by aguynamedryan** [comment]
"Co-reported" under CDMv4 Plus is just if an event shares a visit_occurrence in common with another event, yes?

**Comment by jenniferduryea** [comment]
Yes.  You got it.

**Comment by aguynamedryan** [comment]
Correction to [an above comment](https://github.com/outcomesinsights/conceptql/issues/56#issuecomment-240228346) but apparently this operator was never implemented at all.  I'll implement it for OMOP now and we'll update it for OI CDM later.

**Comment by aguynamedryan** [comment]
Seems to be a bug in this operator.  It generates queries with ambiguous columns.  Could be an interaction with dynamic columns

**Comment by aguynamedryan** [comment]
I think I've fixed the problem.  Frustratingly, the syntax worked just fine under PostgreSQL.

**Comment by marc-outins** [comment]
@aguynamedryan I tested this and don't think it's working.  I first joined synpuf_full.condition_occurrence and procedure_occurrence and found a visit_occurrence that had icd9 427.69 with cpt4 85610.  So I created the algorithm "Test Co-Reported Operator" and added it as an index event to a study and exported it.  The export returned zero results.

**Comment by aguynamedryan** [comment]
I created an additional test in ConceptQL to ensure that co-reported works between condition_occurrence and procedure_occurrence tables and it passed.

Did you test the SQL generated by the algorithm itself, rather than the algorithm in the study?

0 results in a study can come from baselines being too short and many other filtering steps.

If the SQL from the algorithm fails to yield a result, that's a much more convincing test.

**Comment by marc-outins** [comment]
Confirmed that co-reported is now working.

**Comment by jenniferduryea** [comment]
created a study where a patient had to have an icd9 code and hcpcs code with the same visit_occurrence_id.  Confirmed the study picked up that person and correct event.  Closing this out.
