### ISSUE TITLE
Integrate "AND" and "OR" into ConceptQL

### ISSUE THREAD

**Issue by jenniferduryea** [outcomesinsights/conceptql#57]
This request comes from client with Rally ticket https://rally1.rallydev.com/#/48822098710d/detail/userstory/58516092764

Wording from ticket:

> As a programmer, I would like to have “AND”, “OR” etc. as options instead of “Intersect” “Union”. Since “Intersect” is not the same when using with two streams vs. one stream this can be confusing. I would suggest one of two options.
> 
> a.       I believe the easiest option would be a warning of sorts. When someone chooses “Intersect” with two streams it could pop up a warning asking you to change to “Union” since it will be defaulted to “OR”.
> b.      The other option would be to give the options “AND”, “OR”. If you choose “AND” with two streams then the syntax on the back end could change automatically to give the desired results. I imagine this would be more difficult if possible at all.

This might not be relevant since we are trying to remove the Intersect option.  Assigning to @markdanese for prioritization.

**Comment by markdanese** [comment]
I like the word Union.  I agree that Intersect is generally a problem.  I am going to put this as a low priority until we get Intersect sorted out.

**Comment by aguynamedryan** [comment]
I'm going to make the executive decision to _not_ implement this.
