### ISSUE TITLE
Create Provider operator in JAM to search the specialty field

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#64]
Jen proposed the following:
Create a Provider operator where you can add the concept_ids associated with the specialty you are interested in looking at. You would then intersect the Condition_occurrence stream with the list of providers found from the Provider operator to get all of the Condition_occurrence records with those providers.

See https://github.com/outcomesinsights/jigsaw/issues/196 for further details

**Comment by aguynamedryan** [comment]
I'm hoping to avoid using Intersect, especially when it would behave in an odd fashion when fed output from Provider.

Instead, I'm thinking that much like #55 and #54, we'd create a filter that would remove all events that didn't match a set of providers defined by specialty concept_ids.

**Comment by aguynamedryan** [comment]
How do we want to specify the specialty?  By word or by concept_id?

**Comment by jenniferduryea** [comment]
CMS specialty vocabulary concept ids

**Comment by aguynamedryan** [comment]
Just to clarify, the place of service operator (#61) takes actual CMS codes as arguments, not concept_ids.  The place of service filter operator (#54) will take actual CMS codes as well.

**Comment by jenniferduryea** [comment]
please allow user to add in concept_ids.  The source codes are pretty obscure and a user will have to look up what the codes mean in documentation. Might as well look up the concept_id.

**Comment by markdanese** [comment]
The Provider filter shows up in the JAM as "new operator" and has no properties/parameters.

**Comment by aguynamedryan** [comment]
Actually, adding the Provider Filter to the JAM caused it to die silently.

I have fixed this bug.

**Comment by marc-outins** [comment]
I can confirm we can now add algorithms with the Provider filter.  Synpuf does not have specialty type so I can't test it.

**Comment by marc-outins** [comment]
I created fake specialties for the synpuf_250 data with specialties General Practice (concept_id 38004446) and Physician Assistant (concept_id = 38004512). 

I confirmed the filter is working and the resulting events file includes the providers id.  @aguynamedryan Should we also include the specialty name or id?

**Comment by aguynamedryan** [comment]
@marc-outins, we can, but that should be a separate ticket for a later release.

**Comment by jenniferduryea** [comment]
confirmed an event is included if the associated provider for that event has that specialty.  Tested with different specialties and confirmed when a patient was included or not included.  Looks great.  Closing out.
