### ISSUE TITLE
Fix except operator for Impala

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#66]
Isn't natively supported under Impala, and our work around uses a lot of group by statements, which is hard on Impala (we think)

This fix is a rewrite of the Except operator. Hopefully this will use less memory. Test to make sure the operator still behaves as normal.

**Comment by marc-outins** [comment]
Confirmed that Except worked by running export of study Test Unstable Angina Except Outpatient which looks for unstable angina icd9 codes except outpatient and the only events returned were inpatient.  I've checked to make sure there are outpatient records returned for the icd9 codes alone.

**Comment by jenniferduryea** [comment]
confirmed this works.  Closing out.
