### ISSUE TITLE
Change OneInTwoOut to use new require_column feature

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#68]
I've just updated ConceptQL so we can add arbitrary columns to the set of columns returned by a statement.

We can probably require a column or two in the 1in2out operator that will let us simplify the query.

**Comment by marc-outins** [comment]
@aguynamedryan What are we testing with this one?

**Comment by marc-outins** [comment]
I confirmed 1in2out is working and exports the provenance type concept id

**Comment by jenniferduryea** [comment]
Confirmed the provenance type column is added to the events table (from exports).  The provenance type column populates the table with the condition_type_concept_id found from an algorithm that uses the 1in2out operator.  Also confirmed that an algorithm without a 1in2out algorithm did not have a populated provenance type field.
