### ISSUE TITLE
Set RUNTIME_FILTER_MODE=off

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#70]
We need to make sure this setting is passed to Impala before executing queries.  If we do not pass in this setting, some of Jigsaw's operators behave in a non-deterministic way.

**Comment by aguynamedryan** [comment]
The logs from sidekiq should show a line like "SET runtime_filter_mode=OFF" when first starting an export.

**Comment by aguynamedryan** [comment]
I'm seeing it in the log files and in the export_queries table

**Comment by jenniferduryea** [comment]
Confirm I can see "SET runtime_filter_mode=OFF" in sequence_line=1 of the export_queries table from the export files.  Closing out.
