### ISSUE TITLE
Change text of provenance operator

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#71]
Removing the last part since this is covered already in the operator.  The correct text is below.

Filters incoming events to those with the indicated provenance. Enter numeric concept id(s), or the corresponding text label(s) (e.g., "inpatient", "outpatient", "carrier").

---
Moved from outcomesinsights/jigsaw#243
/cc @markdanese

**Comment by claire-oi** [comment]
I see this text for the provenance operator.

**Comment by jenniferduryea** [comment]
Confirm I see the new text in information card of the JAM and JAV as outins.
