### ISSUE TITLE
Change text for POS filter

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#72]
Please change the text to the following:

Filters records to include only those that match one or more of the Medicare Place Of Service values.  Common values include 21 (inpatient hospital), 23 (emergency room), and 11 (office).

---
Moved from outcomesinsights/jigsaw#244
/cc @markdanese

**Comment by jenniferduryea** [comment]
Confirm I can see the new text on the information card in the JAM and JAV.

**Comment by markdanese** [comment]
The text is there and it matches the above.
