### ISSUE TITLE
Update ConceptQL to read from OI_CDM database

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#73]
ConceptQL will need to query the OI_CDM. 

Use case:  OI Project for SEER Medicare data.  Marc will do ETL and Ryan will need to change conceptQL to run it.

asana task https://app.asana.com/0/82031366851235/114546449360971

---
Moved from outcomesinsights/jigsaw#69
/cc @jenniferduryea @aguynamedryan

**Comment by aguynamedryan** [comment]
This has been done enough to get the NCI demo working.

However, we are still pending the following functions:

- Dynamically detect domains in vocabulary operator
  - Sortaworking
- Add domains to each voacbulary? concept?
- Operator#person_table
- Map SEER gender and have Gender use it
- Need complete reworking
  - Complement
  - Casting
  - One in Two Out
- Deprecate These Operators
  - Drug Type
  - Condition Type
  - Place of Service
  - Observation Period
    - Replace with "information period"
- Gender pulls no patients by common concept ID

No rows to test:
- LOINC
- ICD10*
- NDC
- Race
- Revenue code
- RxNorm
- SNOMED

**Comment by aguynamedryan** [comment]
needs #74 
needs #75
needs #76 
needs #77 
needs #78 
needs #79 
needs #106 
needs #115 
needs outcomesinsights/jigsaw#349

**Comment by jenniferduryea** [comment]
Moving this to chisel since this is not dependent on Amgen's release.

**Comment by aguynamedryan** [comment]
At this point, ConceptQL exclusively supports GDM.  We do still need tests for various vocabularies listed above though.

**Comment by aguynamedryan** [comment]
Turns out data needed for tests is covered int #191.  Closing
