### ISSUE TITLE
Require Vocabulary Files in Order to Support Dynamic Domains for OI CDM

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#74]
The purpose of this ticket is to remind us we need to be able to tell ConceptQL where to find its vocabulary files for OI CDM.  The rest of this ticket lays out how dynamic domains will work with OI CDM.

We just got the slightest bit of dynamic domains working in ConceptQL (b7b970d56210c228748c8ccb056270fd6dc9d71d) but, in the absence of vocabulary files, it is hard to determine which domains an algorithm is dealing with.  Because each OMOP database carries its own vocabulary files, an algorithm can't know what domains it's dealing with until it is told which database it will be run against.

OI CDM will make extensive use of dynamic domains and it is critical that algorithms be able to determine their domains without being fed a specific database.  Fortunately, because OI CDM performs mapping on the fly, rather than at the time of ETL, databases won't be tied to a specific set of vocabularies.  In fact, it's likely that only a single set of vocabulary files will be needed for a set of databases and ConceptQL can use that set of vocabulary files to determine domains.

**Comment by aguynamedryan** [comment]
Related to #121

**Comment by aguynamedryan** [comment]
#121 is a poor-man's version of this feature.  Unless ConceptQL carries around a library of all known codes (essentially, the GDM concepts table), it cannot get enough granularity to accurately predict what types of results are generated by an algorithm.

outcomesinsights/jigsaw#386 would be a better way to implement this feature.  Punting until that ticket is implemented.

needs outcomesinsights/jigsaw#386

**Comment by aguynamedryan** [comment]
Now that we have Lexicon for ConceptQL, I don't know that this ticket is needed anymore?

**Comment by jenniferduryea** [comment]
agreed.  Closing.
