### ISSUE TITLE
Rework Casting

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#76]
Casting may not even make sense under OI CDM.  I've long believed that if an algorithm contains a casting operator, it implies that ConceptQL is missing some more useful and appropriate operator.  E.g. We made the PlaceOfServiceFilter operator to avoid casting conditions/procedures into visits to intersect them with ConditionType

Perhaps it is time to retire casting.  If not, we'll have to revisit this ticket and devise a sensible casting matrix as we did for OMOP

**Comment by markdanese** [comment]
In the OI CDM paper, we identify the fact that most data models use the visit as a way to connect pieces of information together.  We have formalized that idea as "contexts" in OI CDM.  To some degree collections might be involved in connecting pieces of information when the connection is broader (at the visit or claim level).  I would imagine that most casting would be referring to a shared context or possibly shared collection.

**Comment by aguynamedryan** [comment]
@markdanese, is what you're talking about related to outcomesinsights/jigsaw#375

I'd like to review how we're using casting operators and what we can do to avoid their use and simplify the algorithms that currently employ them.

**Comment by jenniferduryea** [comment]
We go into a lot more detail about these in outcomesinsights/jigsaw#379 .  @aguynamedryan do you still need more clarification?

**Comment by aguynamedryan** [comment]
@markdanese, @jenniferduryea, have we decided to remove casting operators?

**Comment by jenniferduryea** [comment]
I believe #142 has made casting operators optional. I'm ok with removing them.

**Comment by markdanese** [comment]
Sure.  Good for me too.  Do we need to migrate any of Amgen's algorithms?

**Comment by jenniferduryea** [comment]
Yes we do.  Let's create a new ticket with a list of casting operators we are going to remove and then we can search for all existing algorithms.  I can then coordinate with Fangfei about how to go about doing this.

**Comment by jenniferduryea** [comment]
move this to chisel since this is not necessary for broom.

**Comment by aguynamedryan** [comment]
Implementing #92 would make searching for casting operators much easier.

needs #92

**Comment by aguynamedryan** [comment]
Casting has been removed from ConceptQL as it is no longer required.
