### ISSUE TITLE
Deprecate Operators

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#78]
Some operators are overly OMOP-specific and should be deprecated.

The following are subsumed by the new Provenance operator (a9365ee33b45d33d836333cb52fe155ec76485cf)
- Drug Type
- Condition Type

PlaceOfServiceFilter (83b0936d347a944ccb7c6b267d8d84e5e7894561) replaces most uses for the PlaceOfServiceCode operator, though we'll probably want to keep both, for the off chance an algorithm needs all visits from a certain place of service, though I can't think of a specific use case.

**Comment by aguynamedryan** [comment]
Currently, here are the counts for algorithms that use the following deprecated algorithms:

- drug_type_concept - 0
- condition_type - 44
- place_of_service_code - 57

I'd still like to deprecate these operators.  By that I mean avoid updating them to work with GDM, and mark them as deprecated in the JAM (somehow).  We'll support them through Broom, for omopv4_plus, but remove them in Chisel.

Does that seem acceptable?

**Comment by aguynamedryan** [comment]
I'm also considering deprecating Complement and avoiding having that work under GDM as well.  There are 17 uses of complement, and all are applied to place_of_service_code to find all non-inpatient visits.

I'd rather update the place_of_service_filter to allow users to exclude a set of service codes.

**Comment by jenniferduryea** [comment]
Deprecating complement seems reasonable.  I have to see if condition_type and place _of_service is always intersected with an selection operator (i.e. icd9 operator) or if there are occasions to just find all conditions with a certain type_concept_id or visits with a certain place of service code.

**Comment by markdanese** [comment]
One need we will have is to identify all hospitalizations or all emergency room visits or things like that.  We could think about a "visit" operator to allow people to find these things, subject to some reasonable parameters that people might want to specify (e.g., facility or physician).

**Comment by markdanese** [comment]
(the "visit" operator is intended to be different from our current casting operator)

**Comment by aguynamedryan** [comment]
3ec9f55 deprecates:

- ObservationPeriod (in favor of InformationPeriods)
- PlaceOfServiceCode (in favor of PlaceOfServiceFilter)
- DrugTypeConcept/ConditionType (in favor of Provenance)

**Comment by jenniferduryea** [comment]
Responding to:  "I'd still like to deprecate these operators. By that I mean avoid updating them to work with GDM, and mark them as deprecated in the JAM (somehow). We'll support them through Broom, for omopv4_plus, but remove them in Chisel."

That seems reasonable to me.  Just to confirm that any existing algorithms will still work.  But users will be prevented from creating new algorithms with the deprecated operators.

**Comment by markdanese** [comment]
Depending on how many algorithms there are, we can consider rebuilding algorithms (for Amgen) that use deprecated operators and then remove the operator **completely**.  It would be nice if we can minimize support for keeping deprecated operators working.

**Comment by aguynamedryan** [comment]
operator | count
-- | --
drug_type_concept | 0
filter | 0
observation_period | 0
started_by | 0
procedure_occurrence | 1
race | 1
snomed | 1
trim_date_end | 1
trim_date_start | 1
loinc | 2
rxnorm | 2
any_overlap | 3
concurrent_within | 3
gemscript | 4
person | 4
drg | 5
icd10_pcs | 5
last | 5
overlapped_by | 5
gender | 6
contains | 7
equal | 7
overlaps | 7
occurrence | 8
death | 10
cpt | 11
observation_by_enttype | 11
person_filter | 15
complement | 17
provider_filter | 18
date_range | 22
revenue_code | 22
place_of_service_filter | 26
condition_type | 44
before | 46
co_reported | 46
after | 47
visit_occurrence | 52
first | 55
during | 57
place_of_service_code | 57
read | 60
except | 61
intersect | 75
time_window | 77
icd10 | 95
recall | 101
provenance | 121
cpt_or_hcpcs | 123
hcpcs | 177
one_in_two_out | 191
ndc | 345
union | 547
icd9_procedure | 613
icd9 | 1353

**Comment by aguynamedryan** [comment]
Perhaps I should make it so that deprecated operators aren't available if the Jigsaw instance is using GDM?

**Comment by aguynamedryan** [comment]
@jenniferduryea, @markdanese I plan to hide deprecated operators if Jigsaw is set to operate against GDM

**Comment by jenniferduryea** [comment]
Sounds good to me!

**Comment by markdanese** [comment]
Yes.  I agree.  Does this mean that deprecation can vary by data model?

**Comment by jenniferduryea** [comment]
We need to test this against a gdm db.  Also, this can wait till chisel.

**Comment by aguynamedryan** [comment]
@markdanese, to answer your question from a year ago, good point.  At the moment, if an operator is deprecated, it is deprecated for all data models.

However, we now have situations where some algorithms only appear in GDM (mostly the vocabulary-based operators unique to GDM-related vocabularies (e.g. SEER_SEQ operator))

Currently, this isn't a big deal because a Jigsaw instance only supports a single data model.  e.g. broom.jsaw.io is using OMOPv4+ everywhere and can't use GDM.  So all algorithms made in broom are consistent with the OMOPv4+ set of operators.

This is probably a Bad Idea in the long run once we allow Jigsaw to support different data models based on the data model used for a particular claims database. e.g. if Amgen uses GDM for SEER, but OMOPv4+ for marketscan, Jigsaw will (someday) generate GDM-compatible queries when exporting against SEER and OMOPv4+ queries when running against marketscan.

Since, eventually, we want to share algorithms between Jigsaw instances, we also need to be able to handle situations where an algorithm's ConceptQL statement uses operators unique to a data model.  I've added #192 to possible address this issue.

**Comment by aguynamedryan** [comment]
I realize I didn't address the state of this ticket.  I don't think we're seeing deprecation warnings right now.  I'll need to look into this and would like to put any needed fixes in as a patch to Broom. @jenniferduryea, do we have a milestone for the next Broom patch (18.06.02)?

**Comment by aguynamedryan** [comment]
Just as an update, here are the operators currently marked as deprecated, along with their replacements.

- Overlaps => AnyOverlap
- OverlappedBy => AnyOverlap
- PlaceOfServiceCode => PlaceOfServiceFilter
- Intersect => ["Provenance", "Place of Service", "Provider"]
- Complement
- VisitOccurence => PlaceOfServiceFilter
- ObservationPeriod => InformationPeriod
- ProcedureOccurrence => Provenance
- ConditionType => Provenance
- DrugTypeConcept => Provenance

**Comment by aguynamedryan** [comment]
I'd like to actually remove these operators now.  Any objections?

**Comment by jenniferduryea** [comment]
@aguynamedryan are there any algos in outins.jsaw.io that use these operators?  If no, then I'm ok with removing them from Jigsaw.

**Comment by aguynamedryan** [comment]
I'm going to consider this work as done.  If there are other operators we'd like to deprecate or remove, we'll create a new ticket.
