### ISSUE TITLE
Rename ObservationPeriod to InformationPeriod

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#79]
Information periods can represent payer or observation periods, so we'll rename ObservationPeriod to InformationPeriod and extend it to cover payer_plan_period and observation_period tables from OMOP and informatoin_periods in OI CDM

**Comment by aguynamedryan** [comment]
I was a bit too vague on this ticket.  Let's nail down exactly how we want this operator to behave.

**Comment by aguynamedryan** [comment]
This ticket _might_ have been created as a way to help users select enrollment periods in the Study Builder, but we are going to have a different way of doing that now.

We'll still need an information_period operator for GDM, and we can still support plan information from OMOPv4.5+ and GDM using this operator.

In order to support plans, we need some way to map plans under GDM.  That way, if someone wants "HMO" records, we know what that means in GDM and in OMOP.

So, for now, this operator will pull all information_period records in GDM and all observation_periods in OMOPv4.  ObservationPeriod operator will be an alias for this operator to maintain backwards compatibility with existing algorithms.

**Comment by aguynamedryan** [comment]
I left ObservationPeriod as its own class so that I could mark it deprecated.

I added InformationPeriods and it will pull all GDM information_periods or all omopv4_plus observation_period records.

**Comment by jenniferduryea** [comment]
we need a gdm db to test this against. moving to broom.

**Comment by jenniferduryea** [comment]
@aguynamedryan I cannot view the SQL or JSON generated from an algorithm using the Information Period operator.  Here is an example of the conceptql diagram I'm using:

[["during",{"left":["icd9","412"],"right":["information_periods"]}]]

The screen that shows the SQL generated is blank.

**Comment by aguynamedryan** [comment]
I'm able to after creating a copy of the statement in this algorithm: http://broom.jsaw.io/algorithms/f429d4ea-96f3-4d18-8902-ade44446d51f/diagram?activeTab=sql

**Comment by jenniferduryea** [comment]
Weird.  Ok I can see it now too.  Closing this as fixed.
