### ISSUE TITLE
Make runtime_filter_mode=off configurable

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#81]
Needs outcomesinsights/jigsaw#265

Sent to Anvil 11.16.1.

When running latest release, Leey ran into an issue where exports were failing because we are adding "runtime_filter_mode=off" for our exports. This was to address issues in Dev running on Impala 5.8. PROD does not recognize this command because it is running on a previous version of Impala.

Jigsaw needs to make this code configurable so that users can remove this line of code when running on Impala version prior to 5.8.

---
Moved from outcomesinsights/jigsaw#266
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
Needs #80

**Comment by aguynamedryan** [comment]
I had to rush a patch out this morning so I hard-coded this configuration option.

For dev, I'd like to implement a more robust feature so we can pass arbitrary settings into a database via ENV and options.

**Comment by aguynamedryan** [comment]
#82 should now allow this feature to work, but we'll need #83 to convert the .env variable names.

Needs #82
Needs outcomesinsights/jigsaw#270

**Comment by jenniferduryea** [comment]
@aguynamedryan to test and close.

**Comment by aguynamedryan** [comment]
Seems to be working for the client.  Closing.
