### ISSUE TITLE
Allow arbitrary parameters to be set through ENV and options

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#82]
In order to avoid situations like #80 in the future, I'd like us to be able to pass in any kind of setting via ENV or the options hash.

I propose that we have a convention for naming environment variables and options keys that will indicate the values stored in those keys should be put into SET statements for the database.

I propose that the convention be:
<DB_TYPE>\_DB_OPT\_<DB_SPECIFIC_OPTION_NAME>

e.g.

IMPALA_DB_OPT_MEM_LIMIT=20g would cause ConceptQL to issue this command to an Impala cluster upon establishing a connection:
```SQL
SET mem_limit=20g;
```

**Comment by jenniferduryea** [comment]
@aguynamedryan to test and close.

**Comment by aguynamedryan** [comment]
Seems to be working for the client.  Closing.
