### ISSUE TITLE
Comprehensive, Specialized Vocabularies

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#91]
Working off the idea introduced in #51, and tying into outcomesinsights/jigsaw#336, I'd like to derive a set of vocabulary files for ConceptQL that:

- Would be used for code lists
- We'd have build scripts that would incorporate upstream changes from OHDSI vocabs as they are updated
- Can we supplement popular vocabularies with historical information about when a code is introduced/removed?

**Comment by aguynamedryan** [comment]
@jenniferduryea, I'm not sure why this is in Anvil.  It's definitely more of a Broom thing.

**Comment by jenniferduryea** [comment]
Let's move it.

**Comment by aguynamedryan** [comment]
We did this.  It's called Lexicon
