### ISSUE TITLE
Generate Additional Metadata

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#92]
We can inspect a ConceptQL statement and derive all sorts of information about it, such as:

- Which vocabularies are used?
- Is OneInTwoOut used?
- What types come out as a result?

It would be nice to include all of this information as part of the annotation for a statement.

**Comment by aguynamedryan** [comment]
What defines a codeset-only algorithm?

- Definitely
  - `["icd9", "412"]`
  - `["union", ["cpt", "00000"], ["icd9", "412"]]`
- Maybe?
  - `["time_window", ["icd9", "412"], {start: "1d", end: "1d"}]`
  - `["first", ["icd9", "412"]]`
  - `["provenance", "inpatient", ["icd9", "412"]]`
- Most Likely Not
  - `["after", {left: ["icd9", "412"], right: ["icd9", "410.00"]}]`

**Comment by aguynamedryan** [comment]
Here is the list of metadata I believe we can automatically determine from a ConceptQL statement:

- Codeset Only?
- Does the algorithm calculate a value for each person?
  - This will, for the moment, always be no since ConceptQL doesn't (yet) do this
- Are any selection operators limited by positions of the code?
  - e.g. primary diagnoses only
- Are any selection operators limited by the file from which the code comes from?
  - e.g. inpatient file only

What other qualities would we like to know about an algorithm?

**Comment by markdanese** [comment]
In my mind, **codeset only** is something that is a codeset with no other operation, except to union together code sets.  It is just a way of representing a list of codes that represent a clinical idea or event.  It is the bottom of our hierarchy: ```codeset -> algorithm -> cohort -> study``` 

I am not sure if there are any other operators that modify code lists (except?).  

(I recognize that a codeset is the simplest algorithm, of course.)

**Comment by aguynamedryan** [comment]
This stuff is handy, but still poorly defined and we're coming up on releasing Broom.  Chisel it.

**Comment by aguynamedryan** [comment]
- Count of codes in the statement
  - How do we handle '*'?
- How "deep" is algorithm?
- How "wide" is algorithm?

**Comment by aguynamedryan** [comment]
Looks like d8775f52f8836c5b1ec213e0086f0f0728853459 completes this.
