### ISSUE TITLE
Validations Raise Exception Without Vocabulary Tables

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#96]
We should handle database errors more gracefully.  Validations will now check for the vocabulary tables before trying to use them.  If the tables aren't there, we'll just not perform those validations.

This will address outcomesinsights/jigsaw-diagram-editor#327

**Comment by aguynamedryan** [comment]
The only validation this impacts at the moment is getting back warnings about codes/concepts that aren't in the vocabulary tables.  All other errors and warnings should still work.

**Comment by aguynamedryan** [comment]
needed-by outcomesinsights/jigsaw-diagram-editor#327

**Comment by aguynamedryan** [comment]
Addressed by b36bab1782a07212511e2e05bdbeb7b2b1ca0bf6

**Comment by jenniferduryea** [comment]
Tested this on the client's end after the update and works as expected.  Closing out.
