### ISSUE TITLE
Create PostgreSQL Container with ConceptQL Test Data

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#97]

**Comment by aguynamedryan** [comment]
I'll provide the pg_dump file for the databases in question.  Someone just needs to containerize them.  It'd be a good opportunity to see if a container running PostgreSQL 9.6 is significantly faster than a container running 9.5

**Comment by aguynamedryan** [comment]
What I'd *really* like is a script that takes a pg_dump file as an argument and spits out a Docker image with all the data loaded into it.

**Comment by dominickm** [comment]
Ok so to be clear -- what you want is: 

A script that takes as a param a pg_dump and generates a Postgres 9.6 container seeded with that data?

**Comment by aguynamedryan** [comment]
Yes, please.

**Comment by dominickm** [comment]
I have an ansible playbook for this. Didn't know I couldn't upload it here sending in email.

**Comment by aguynamedryan** [comment]
I've pretty much got this working how I'd like.
