### ISSUE TITLE
Create ICD-10 diagnosis operator to query both vocabulary 34 and 70

### ISSUE THREAD

**Issue by aguynamedryan** [outcomesinsights/conceptql#99]
There has been some confusion from OMOP vendors as to when to use vocabulary 34 vs. vocabulary 70 when mapping ICD-10 diagnosis codes.  So even for OMOP v4.5+, vendors would assign vocabulary_id 34 or 70, depending on what version of the vocabularies they are using.  Since there is a lot of overlap between vocabularies, we need to create a conceptql operator that will query both vocabulary 34 and 70 for ICD-10 diagnosis codes.  This would be similar to the CPT/HCPCS operator already available.

---
Moved from outcomesinsights/jigsaw#324
/cc @jenniferduryea

**Comment by aguynamedryan** [comment]
1306974

**Comment by jenniferduryea** [comment]
Confirmed that this operator will query both vocabulary 34 and 70.  Also note that the ICD10 operator has been named "ICD-10 Conditions".  I noticed that the operator is grey instead of red.  Please see screenshot below:
![image](https://user-images.githubusercontent.com/7853238/28342609-f6742b38-6bcd-11e7-8955-ef5811b76382.png)

Shouldn't this operator be red since it is looking at conditions?

**Comment by aguynamedryan** [comment]
We don't know the domains of any of the vocabularies yet, so no colors :-(

**Comment by jenniferduryea** [comment]
Will vocabulary assignments be available in this release?

**Comment by aguynamedryan** [comment]
@jenniferduryea, if you mean #106 and #91, then yes.  But, for now, we don't have domain information for the vocabulary file.

**Comment by jenniferduryea** [comment]
Ok this ticket has been tested to show that this operator is querying both ICD10 vocabularies and the name of this operator is called "ICD-10 Conditions".  I will open another ticket to address the color of the operators.

**Comment by marc-outins** [comment]
Confirmed that ICD-10 Conditions operator exists.  And the SQL code generated when looking at the JAM code generator looks correct.  I will say to me it's confusing the difference between ICD-10 Conditions and ICD10-CM.  I would suggest we add more detail in the information card.
